### ISSUE TITLE
`spc t w` should be assigned to editor.action.toggleRenderWhitespace

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#101]
**Is your feature request related to a problem? Please describe.**
Currently `spc t w` is assigned to `toggle.diff.ignoreTrimWhitespace`.

**Describe the solution you'd like**
The spacemacs behavior is the one of the `editor.action.toggleRenderWhitespace` action, i.e. "View: Toggle Render Whitespace".

Do you know to which key binding should we move the `editor.action.toggleRenderWhitespace` action?

**Comment by stevenguh** [comment]
Maybe we can move the current key into a diff menu (like imaging `<spc> x d` / `<spc> t d`)?

**Comment by MarcoIeni** [comment]
both are already taken in spacemacs.
In my opinion we can use `<spc> t d`, since spacemacs uses it to toggle hungry delete which, from what I've seen, if enabled deletes all the whitespaces instead of only one when you type "backspace". It doesn't seem so useful to me and I don't think there is a similar function in vscode.

**Comment by stevenguh** [comment]
That sounds good to me :)

**Comment by MarcoIeni** [comment]
I just noticed that `SPC D` in spacemacs is dedicated to "diff/compare".
`SPC D W` (for Whitespace) and `SPC D t` (for trim) are available.

**Comment by stevenguh** [comment]
Even better 🚀

**Comment by MarcoIeni** [comment]
closed by 381f77ad7ee8472f7414841eb4eb82be02ac978b and 0f42e3a84f53290e90b825b0b48a03d008a94c2c

**Comment by MarcoIeni** [comment]
I decided to change key bindings of `SPC D` with respect to the one of spacemacs, because they were not really applicable.
If someone wants to discuss this choice, please comment.
