### ISSUE TITLE
.github repository

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#109]
**Is your feature request related to a problem? Please describe.**
There is some duplication among VSpaceCode repository, for example issue and pull request template.

**Describe the solution you'd like**
I was also thinking about setting up a `.github` repository, in order to remove duplicated templates among all the repos. [Here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file#creating-a-repository-for-default-files) you can find the documentation about it.
I think that you can write default templates on this repo and they will be applied to all the repo, unless one repo specifies its own template.

**Additional context**
 Example [here](https://github.com/actions-rs/.github).

**Comment by stevenguh** [comment]
This sounds good :)

**Comment by MarcoIeni** [comment]
Waiting for #110 to be discussed.

**Comment by MarcoIeni** [comment]
I created the [.github](https://github.com/VSpaceCode/.github) repo.

Relevant commits:
- vspacecode.github.io:
  - https://github.com/VSpaceCode/vspacecode.github.io/commit/5cb9120770d0f27a390b7225aac0a814c8279577
- https://github.com/VSpaceCode/vspacecode.github.io/commit/42323346a6d3b7c046b0c9471af410cd19b3e59c (I had to duplicate the other files because apparently you cannot override just one issue template)
- VSpaceCode:
  - f372a136255b9be3284bd9f2cc0a932f94c23ba2
  - bb3d59a0a2ce34723f678d7fc2909b508196dd64
- which key:
  - https://github.com/VSpaceCode/vscode-which-key/commit/59f9b73b0528980239ec6891cce852b580bd6ce8
  - https://github.com/VSpaceCode/vscode-which-key/commit/ee6883935e4314878404e322b4dd7d449ff611d0

**Comment by MarcoIeni** [comment]
I left out pull request template because it doesn't apply to all the repos
