### ISSUE TITLE
Ability to use native VSCode functionality around Git

### ISSUE THREAD

**Issue by blasterpistol** [VSpaceCode/VSpaceCode#113]
**Is your feature request related to a problem? Please describe.**
I am happy with standard git panel and timeline panel functionality and never use Magit, cause my requirements a small and generally covered by git flow extension commands.

**Describe the solution you'd like**
I would like to map some keyboard shortcuts to the standard "Git: *" commands and possibly have better navigation in the git and timeline panels. I checked out "community-configs", but it's a bit far from consistent bindings to standard git actions.

**Comment by stevenguh** [comment]
You can use the [overrides](https://vspacecode.github.io/docs/menu-customization#incrementally) to change the git sub-menu with your commands, you can also look at the which-key's [default `g` sub-menu](https://github.com/VSpaceCode/vscode-which-key/blob/v0.8.1/package.json#L484-L550) which doesn't use any third party dependency.

**Comment by MarcoIeni** [comment]
We could have `<spc> G` to work with standard VSCode git client. While `<spc> g` stays with magit.
blasterpistol, do you want to work on that if Steven agrees on this idea?

**Comment by stevenguh** [comment]
If the assumption is people would use both magit and native git, it makes sense to have both.

If most people will only use one or the other, overrides is one way to go. The other way is to have a conditional binding for `g` that depends on settings (some engineering work required)

I would vote for having overrides documented in the short-term until we have more request from the community.

**Comment by MarcoIeni** [comment]
> I would vote for having overrides documented in the short-term

What would you document? Aren't overrides already documented in the website?

Plus, we have the macintacos [key bindings](https://github.com/VSpaceCode/community-configs/blob/6a4ffd4dda8213c3729b897d8d60f020639196e8/macintacos/vspacecode-config.json#L401) which represent a really good example (we could link it in the website).

**Comment by stevenguh** [comment]
I was thinking documenting a default native git commands menu overrides in the bonus section of the website. However, on second thought, maybe what we have is enough :)

**Comment by MarcoIeni** [comment]
Ok, so this can be closed I think.

I just want to point out for future reference that some actions for VSCode git client are present in the vscode-vim branch:

https://github.com/VSpaceCode/VSpaceCode/blob/c8f1370a5fd3801f0cb713214ab235971835b9d1/settings.json#L206
