### ISSUE TITLE
Vim remap suggestion for `b.Y`

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#117]
## Problem

Currently, I don't like that `SPC b Y` moves my cursor away from where I am currently positioned. That mapping is currently:

```
{
	"key": "Y",
	"name": "Copy buffer to clipboard",
	"type": "commands",
	"commands": [
		"editor.action.selectAll",
		"editor.action.clipboardCopyAction",
		"cancelSelection"
	]
}
```

## Solution

To fix this, I made the following remapping:

```
{
  "command": "vim.remap",
  "keys": "b.Y",
  "name": "Copy buffer to clipboard",
  "type": "command",
  "args": {
    "commands": [
      {
        "command": ":%y"
      }
    ]
  }
}
```

Works as you'd expect (you'll see the number of lines yanked in the status bar). Wanted to get an opinion on this before I submitted it as a PR, since it feels a bit more elegant.

**Comment by stevenguh** [comment]
Those commands were design for without the usage of vim. Since this repo is design to integrate with vscode vim, I am open to remap it to a better command in vim. However, that command doesn't seem to work for me. Are you using neovim?

**Comment by macintacos** [comment]
Oh darn, yes I am (at least, I have a line in my settings pointing to the neovim binary). I guess I'll keep it as a personal mapping for the time being, since I think the neovim integration was marked as experimental

**Comment by macintacos** [comment]
Let me see if I can figure something out without neovim and close this out if I can't.

**Comment by macintacos** [comment]
Okay yeah I can't figure it out without turning off neovim integration, so I'll just leave this issue here for those who want to enable it 🙂

**Comment by stevenguh** [comment]
Very unfortunate that it seems like they deferred that to neovim integration https://github.com/VSCodeVim/Vim/issues/1732
However, this seems to work
```
        {
            "keys": "b.Y",
            "name": "Yank the whole buffer",
            "type": "command",
            "command": "vim.remap",
            "args": {
                "after": [
                    "g",
                    "g",
                    "y",
                    "G",
                    "<C-o>"
                ]
            }
        },
```

**Comment by macintacos** [comment]
Ah I had forgotten about that motion to be honest. Although now that I think about it, perhaps we should try to leverage VSCode commands directly if we can? Is there a command to "return to previous position" in VSCode that we can just stick at the end there?

**Comment by stevenguh** [comment]
That I am not sure, we can try and find it. btw, what do you think about my remapping?

**Comment by macintacos** [comment]
I like it! If we're okay with just making it a vim command, I say go forward with that option.

**Comment by stevenguh** [comment]
@MarcoIeni What do you think?

**Comment by MarcoIeni** [comment]
I found `workbench.action.navigateBack` to replace `<C-O>`, so I tried to place this inside `package.json` but it doesn't work:
```
{
    "key": "Y",
    "name": "Copy buffer to clipboard",
    "type": "commands",
    "commands": [
        "editor.action.selectAll",
        "editor.action.clipboardCopyAction",
        "cancelSelection",
        "workbench.action.navigateBack"
    ]
}
```

The solution from steven works as expected instead. I will do a PR, because I have already edited `package.json`.
