### ISSUE TITLE
Consider using https://open-vsx.org/

### ISSUE THREAD

**Issue by maxwedwards** [VSpaceCode/VSpaceCode#125]
VSpaceCode isn't available on https://open-vsx.org/ the open marketplace used by vscodium and I think it would be a great addition.

**Comment by stevenguh** [comment]
Related: https://github.com/VSpaceCode/vscode-which-key/issues/16

**Comment by MarcoIeni** [comment]
> Related: VSpaceCode/vscode-which-key#16

Yes, I would like to keep the discussion in that issue, so I will lock this conversation.
Let's discuss this in that issue instead :)

**Comment by stevenguh** [comment]
Seems like if bundled extension doesn't exist in open-vsx, we can't really publish to open-vsx. https://github.com/VSpaceCode/VSpaceCode/actions/runs/416226978

**Comment by stevenguh** [comment]
Reverted all the github actions related to open-vsx on this repo, and manually deployed this time. As far as solutions, I think we might have to either publish all the dependent extensions or wait until all the dependent extensions are published.

**Comment by MarcoIeni** [comment]
Let's open issues on dependent extensions repository and wait until they publish it.
I will do it.

**Comment by MarcoIeni** [comment]
This is the draft of the message that I will copy paste in dependent repositories.

Steven feel free to review it, expecially point 2 of the instructions.

```
Hi! I am one of the maintainers of [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode).

We would like to publish our extension to https://open-vsx.org/ in order to make it easier for people who use IDEs like VSCodium, Theia, etc. to install it.

We already successfully published [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key) to open-vsx.
With [this](https://github.com/VSpaceCode/vscode-which-key/blob/master/.github/workflows/deploy.yml) GitHub action we release it automatically every time you do a `git tag`.

In order to do the same you just need to:
1. Sign in with your GitHub account
2. Set secrets
3. copy paste the GitHub action in your repository
4. create and push a git tag that starts with 'v'
```

**Comment by stevenguh** [comment]
I would say something like

> Hi! I am one of the maintainers of [VSpaceCode](https://github.com/VSpaceCode/VSpaceCode), which bundles your extension.
> 
> We would like to publish our extension to https://open-vsx.org/ in order to make it easier for people who use IDEs like VSCodium, Theia, etc. to install it. However, we are not able to because your extension which we bundled is not published on open-vsx.
> 
> We already successfully published one of our bundled extension, [vscode-which-key](https://github.com/VSpaceCode/vscode-which-key) to open-vsx using an [GitHub Actions](https://github.com/VSpaceCode/vscode-which-key/blob/master/.github/workflows/deploy.yml) to deployed the extension automatically on tag to both Visual Studio Marketplace and Open VSX.
> 
> Publishing extension to open-vsx is very simple and you can follow their [official instruction](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension).

**Comment by MarcoIeni** [comment]
blocking issues:
- https://github.com/kahole/edamagit/issues/93
- https://github.com/jacobdufault/vscode-fuzzy-search/issues/13
- https://github.com/bodil/vscode-file-browser/issues/17

**Comment by mandarvaze** [comment]
Any updates ?
In the mean time, where can I find documentation if I wish to manually install this extension pack (Or is it not at all possible)

**Comment by stevenguh** [comment]
> Any updates ?

I think it's still blocked by upstream dependent extensions not published on open vsx.
1. Ping in issue on the repo of the extensions
2. Publish those dependent extensions without claiming the namespace on Open VSX

If someone is willing to do number 2 for our dependent extensions, we can publish this extension on Open VSX.


> install this extension pack (Or is it not at all possible)

I think you might need to install the extensions in the extension pack manually by using `vsce` command on each source code of each extension that's not on Open VSX: https://github.com/VSpaceCode/VSpaceCode/blob/v0.9.0/package.json#L30-L34.

**Comment by stevenguh** [comment]
A third option is the update https://github.com/open-vsx/publish-extensions to have open vsx publish the missing extensions.

**Comment by mangkoran** [comment]
Hello. I see that both https://github.com/jacobdufault/vscode-fuzzy-search and https://github.com/bodil/vscode-file-browser haven't had recent commit in the past 6 months. Should the extensions published using 3rd option?

**Comment by stevenguh** [comment]
Would love to have someone help publish/make a PR to https://github.com/open-vsx/publish-extensions to open-vsx will publish it.

`vscode-file-browser` should able to publish through this method, however, the lack of license in `vscode-fuzzy-search` is an issue.

**Comment by tbsexton** [comment]
What about another option e.g. [this](https://github.com/tatosjb/vscode-fuzzy-search) fuzzy search plugin? Already has an MIT license, so if that works to get the extensions on vsx we could be back in business here?

**Comment by stevenguh** [comment]
> What about another option e.g. [this](https://github.com/tatosjb/vscode-fuzzy-search) fuzzy search plugin? Already has an MIT license, so if that works to get the extensions on vsx we could be back in business here?

That's a cool extension, but it doesn't replace the `jacobdufault/vscode-fuzzy-search` (this fuzzy search the current buffer). `tatosjb/vscode-fuzzy-search` searches the whole project directory using fzf.

Thinking more about future. Once we implemented layers, VSpaceCode won't bundle any other extensions except whichkey; hence, it can be published though openvsx.

The layers (as vscode extensions) can be installed by users; similar to layer in spacemacs.

**Comment by stevenguh** [comment]
https://github.com/open-vsx/publish-extensions/pull/669 publishes the last blocking extension to OpenVSX, and manually republish the current version of VSpaceCode to OpenVSX.

We are finally on OpenVSX: https://open-vsx.org/extension/VSpaceCode/vspacecode
