### ISSUE TITLE
There is latency after pressing space (or other) key

### ISSUE THREAD

**Issue by onriv** [VSpaceCode/VSpaceCode#127]
## Bug description

If pressing spc or other key continuously (like double press spc), the scecond key press are ignore

## To Reproduce

press `<spc> <spc>` quickly , or `<spc>ff`, or `<spce>bb` quickly. Then the second or third key press are ignored

## Expected behavior

Make `<spc>` response quickly, or give some hints to diagnoe on it. Currently I have to wait some time to press the second key to make it work. It's quite break the workflow.

## Screenshots

screencast like:

![output](https://user-images.githubusercontent.com/1629055/96336901-59ffe680-10b5-11eb-8b20-28502fb4d914.gif)

## System information

CPUs | Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)
-- | --
GPU Status | 2d_canvas: enabled flash_3d: enabled flash_stage3d: enabled flash_stage3d_baseline: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on protected_video_decode: unavailable_off rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 4, 4
Memory (System) | 16.00GB (0.78GB free)

Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 2.1.0
vscode-sql-formatter | adp | 1.4.4
Bookmarks | ale | 11.4.0
All-Autocomplete | Ati | 0.0.23
markdown-emoji | bie | 0.0.9
file-browser | bod | 0.2.10
sqlformatter | bre | 0.0.7
thrift | cdu | 0.0.1
xml | Dot | 2.5.1
gitlens | eam | 10.2.2
graphviz-preview | EFa | 1.4.0
vscode-powertools | ego | 0.61.0
vsc-material-theme | Equ | 33.0.0
vsc-material-theme-icons | equ | 1.2.0
prettier-vscode | esb | 5.7.1
foam-vscode | foa | 0.3.1
vscode-mysql | for | 0.4.0
mdmath | goe | 2.5.1
gc-excelviewer | Gra | 3.0.40
vscode-drawio | hed | 1.0.2
reg | ion | 1.0.1
fuzzy-search | jac | 0.0.3
latex-workshop | Jam | 8.13.2
vscode-edit-csv | jan | 0.4.2
plantuml | jeb | 2.13.14
intellij-idea-keybindings | k-- | 0.2.41
magit | kah | 0.5.1
vscode-gist | ken | 3.0.3
vscode-markdown-notes | kor | 0.0.20
vscode-leetcode | Lee | 0.17.0
csharpfixformat | Leo | 0.0.84
vscode-JS-CSS-HTML-formatter | lon | 0.2.3
codeacejumper | luc | 3.3.2
bash-ide-vscode | mad | 1.11.0
Lisp | mat | 0.1.10
vscode-language-pack-zh-hans | MS- | 1.49.2
python | ms- | 2020.9.114305
remote-wsl | ms- | 0.44.5
powershell | ms- | 2020.6.0
sqltools | mtx | 0.23.0
polacode | pnp | 0.3.4
java | red | 0.69.0
elastic | ria | 0.13.3
text-marker | ryu | 1.11.0
scala | sca | 0.4.5
code-settings-sync | Sha | 3.4.3
vscode-fileutils | sle | 3.0.1
vscode-autohotkey | sle | 0.2.2
markdown-links | tch | 0.8.0
pdf | tom | 1.1.0
org-mode | too | 0.5.0
cmake | twx | 0.0.17
vscodeintellicode | Vis | 1.2.10
vscode-java-debug | vsc | 0.29.0
vscode-java-dependency | vsc | 0.13.0
vscode-java-pack | vsc | 0.10.0
vscode-java-test | vsc | 0.24.2
vscode-maven | vsc | 0.24.2
vim | vsc | 1.17.1
vspacecode | VSp | 0.8.2
whichkey | VSp | 0.8.2
gitblame | wad | 6.0.0
markdown-pdf | yza | 1.4.4
markdown-all-in-one | yzh | 3.3.0
vscode-asciiflow2 | zen | 0.2.0
vscode-proto3 | zxh | 0.5.2

**Comment by MarcoIeni** [comment]
We have to add this question to the troubleshooting section of the website.

I will do this soon :)

**Comment by onriv** [comment]
@MarcoIeni thanks a lot! It's an
excellent extension:D

**Comment by stevenguh** [comment]
I cannot reproduce the issue, the only time that I have similar issue is the first launch of the menu. What is your `settings.json` and the `keybindings.json`?

The screencast is also a bit difficult to see the interactions. I would recommend to record the screen while show the key on screen like with KeyCastr. From what I can see in the screencast, it seems like vim executed the command, and somehow the menu isn't showing? I would also check the developer console to see there's any errors.

**Comment by onriv** [comment]
@stevenguh yeah It should be someway related to vim plugin, I bind a keybinding like:

```json
{
        "key": "shift+alt+y",
        "command": "vspacecode.space"
}
```

using this keybinding, everything works fine~

**Comment by MarcoIeni** [comment]
Onriv, Steven asked for your settings.json and keybindings.json files.
Can you provide them? Also, check if you have something that goes in conflict with `space`.

> I would also check the developer console to see there's any errors.

OT: steven you can consider to add this to the [issue template](https://github.com/VSpaceCode/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by stevenguh** [comment]
> OT: steven you can consider to add this to the [issue template](https://github.com/VSpaceCode/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

added in https://github.com/VSpaceCode/.github/pull/1

**Comment by onriv** [comment]
@stevenguh hello~ here is my config setting: https://gist.github.com/onriv/c8da9aae05a506f77fd0fe58d4fa3bb2

**Comment by stevenguh** [comment]
The latency is expected due to the vim this https://gist.github.com/onriv/c8da9aae05a506f77fd0fe58d4fa3bb2#file-settings-json-L30-L39 vim binding. Vim is waiting for the second input like the other issue https://github.com/VSpaceCode/vscode-which-key/issues/20#issuecomment-712356664

Since we have two issues opened related to a similar underlying issue, I put the documentation tag on this issue for us to track the work to document in our troubleshooting doc.

**Comment by onriv** [comment]
Thanks a lot! I have not noticed that there is a setting like
```json
    "vim.normalModeKeyBindingsNonRecursive": [
      {
        "before": [
          " ",
          "d"
        ],
        "after": [
          "d",
          "d"
        ]
      }
```

I removed it and my problem solved. Now I close the issue and mark my setting to be private (there maybe some private token in it).
