### ISSUE TITLE
add icons to menu

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#130]
Split from https://github.com/VSpaceCode/VSpaceCode/issues/121#issuecomment-711470494

## Problem

It is not easy to understand when a key binding is an action or it is a sub menu.
Right now we manually add "..." at the end.

## Solution

Icons could be added for all the sub menus.
They are listed [here](https://code.visualstudio.com/api/references/icons-in-labels#icon-listing)

We might choose a default icon, but we could also personalize the icon where it makes sense (for example `spc g` could be assigned to the `git-branch` icon).

**Comment by stevenguh** [comment]
You can also try it out by adding `$(icon-name)` to `name` in overrides
For example:
```
    "vspacecode.bindingOverrides": [
        {
            "keys": "g.b",
            "name": "$(git-branch) Blame",
            "type": "command",
            "command": "gitlens.toggleFileBlame"
        }
    ]
```

**Comment by MarcoIeni** [comment]
Is it possible to add a default icon for submenus if one is not present?

**Comment by stevenguh** [comment]
That has to be add to the `which-key` extension. I am a little hesitant, mostly because the icons don't look that good imo and consistent. For example, if some items have icons, some don't, then the items that have icons stick out. If all items have icons, then the icon might not help user to quickly read. If we were to add default icon feature in the which-key, we will probably need to have an option to turn that off.

Meanwhile, maybe we should try some icons and see if the community likes them?

**Comment by MarcoIeni** [comment]
> Meanwhile, maybe we should try some icons and see if the community likes them?

Adding just some of them would be inconsistent.

> icons don't look that good imo 

I tried it and I agree, mixing icons and text doesn't look that great.
Maybe we could just add a `+` character before the text automatically if the text is a submenu.

![image](https://user-images.githubusercontent.com/11428655/97084445-66d18c80-1617-11eb-9a08-9579257b8ee2.png)

In the picture you can compare the different options we have:

1. we add a `+` character
2. we add an icon (the + in this case)
3. We leave the `...` at the end

I vote for 1. So I propose that which key should automatically add the `+` character in front of each binding that has a sub menu.
You can add an option to which key that let users customize the `+` sign. Users can edit it, so they can have an icon or just leave it blank with `""`.

**Comment by stevenguh** [comment]
> I propose that which key should automatically add the + character in front of each binding that has a sub menu.
> You can add an option to which key that let users customize the + sign. Users can edit it, so they can have an icon or just leave it blank with ""

I like this a lot

**Comment by MarcoIeni** [comment]
I close this, I will open a new issue on the which key repo.
