### ISSUE TITLE
<spc> f f not working

### ISSUE THREAD

**Issue by Qwerty2o** [VSpaceCode/VSpaceCode#135]
Hi. I'm really enjoying the extension but I can't get the open file/folder feature to work.
I tried changing it to "workbench.action.files.openFileFolder" but I'm still getting command not found error.
(I'm on linux)

**Comment by stevenguh** [comment]
[File-browser](https://marketplace.visualstudio.com/items?itemName=bodil.file-browser) is used for `<spc> f f` for default, make sure the file-browser extension is installed (it should by default when you installed VSpaceCode)

Also, I think `workbench.action.files.openFileFolder` is macOS only command (see https://vscode.readthedocs.io/en/latest/customization/keyboard-shortcuts/). Use `workbench.action.files.openfile` instead if you prefer built-in command on Linux

**Comment by Qwerty2o** [comment]
> [File-browser](https://marketplace.visualstudio.com/items?itemName=bodil.file-browser) is used for `<spc> f f` for default, make sure the file-browser extension is installed (it should by default when you installed VSpaceCode)
> 
> Also, I think `workbench.action.files.openFileFolder` is macOS only command (see https://vscode.readthedocs.io/en/latest/customization/keyboard-shortcuts/). Use `workbench.action.files.openfile` instead if you prefer built-in command on Linux

I have File-Browser extension installed. 
Tried 'workbench.action.files.openfile', also didn't work.

But then I tried 'file-browser.open' again, restarted again and suddenly it worked (idk what changed). 
So thanks but issue can be closed.
