### ISSUE TITLE
spc 0 to goto filetree window?

### ISSUE THREAD

**Issue by lawrsp** [VSpaceCode/VSpaceCode#138]
in spacemacs, spc 0 can goto the filetree window

**Comment by MarcoIeni** [comment]
lawrsp, do you want to try to solve this issue? :)

**Comment by lawrsp** [comment]
@MarcoIeni  I solved it by add an user setting : 

```
 {
            "key": "0",
            "name": "Focus files explorer",
            "type": "command",
            "command": "workbench.files.action.showActiveFileInExplorer",
},
```

I searched VspaceCode source , but didnot found the key definations

**Comment by stevenguh** [comment]
Here is where we define our default bindings :) It would be great if you can do a PR for this.
Btw, we used `workbench.view.explorer` as the command for `<spc> f t`, not sure where one works better in this case.
https://github.com/VSpaceCode/VSpaceCode/blob/f7786fa3a4fc1da1b07e3fdca2dd81dc059febd9/package.json#L189-L194

**Comment by MarcoIeni** [comment]
lawrsp, in [CONTRIBUTING](https://github.com/VSpaceCode/VSpaceCode/blob/master/CONTRIBUTING.md) it is explained how to debug the extension if you want to try to solve this.

> not sure where one works better in this case

If in spacemacs both those key bindings do the same thing, I think we should have this duplication, too :)

**Comment by lawrsp** [comment]
@MarcoIeni  @stevenguh
yes, spacemacs has both  `<spc> f t`  and  `<spc> 0` 
but they are not duplicated, one is for toggle (same as `workbench.view.explorer`), and the other is to open (same as `workbench.files.action.showActiveFileInExplorer`)

**Comment by stevenguh** [comment]
Thanks :) Merged
