### ISSUE TITLE
Add command to go to keybinding documentation

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#139]
## Problem

There are a lot of commands, and I find myself wishing that I could search through them all. Until https://github.com/VSpaceCode/vscode-which-key/issues/12 is implemented, I think probably adding a command (`vspacecode.openDefaultKeybindingsDocumentation` or something?) that navigates to https://vspacecode.github.io/docs/default-keybindings and then adding it to the `SPC h` menu would be great as a quick win.

## Solution

A command that opens the VSpaceCode Default Keybindings documentation, added to the `SPC h` menu.

**Comment by stevenguh** [comment]
I am open to it, seems easy enough. It does however, sparks another idea that we can modify https://github.com/VSpaceCode/VSpaceCode/blob/master/scripts/keybindings.js so instead of a build time script to the runtime command that generate a markdown buffer of all the current commands. @macintacos Any thoughts?

**Comment by macintacos** [comment]
I like that approach for keybindings! Although if you do that, then I still think a command to open the VSpaceCode documentation in general would be a nice and easy win, especially for folks getting started.

**Comment by stevenguh** [comment]
I am a little busy at the moment, I probably won't have time to do the idea I suggested. But I can add a command to open our website if that's helpful :)

How about a command name `vspacecode.openDocumentationUrl` that opens https://vspacecode.github.io/docs/. The naming will be very similar built-in one, and we can bind it to `<spc> h D` (is there a better suggestion?)

**Comment by macintacos** [comment]
That sounds perfectly reasonable to me 🙂
