### ISSUE TITLE
keybindings under the project menu for running the build and test tasks

### ISSUE THREAD

**Issue by mattr-** [VSpaceCode/VSpaceCode#141]
## Problem

I've been adding VSCode tasks to my projects lately for both build and test and would like out of the box support for running those tasks.

## Solution

I've implemented overrides to run the default build task and default test task that are mapped to `<spc> p b` and `<spc> p t` respectively. 

## Alternatives

None that I've considered, though I'm open to suggestions.

## Additional context

I'm happy to open a PR to upstream my local override but wanted to write an issue first to see if this was already planned or otherwise unwanted before opening a PR. 🙂

**Comment by stevenguh** [comment]
`<spc> p c` is the project compile in spacmacs, which seems similar to build and `<spc> p T` is the test command. We probably should use the similar keybindings as in spacemacs?

**Comment by mattr-** [comment]
I'm fine with that. I never used spacemacs, so I was ignorant to anything they might have done. I'll work on a PR.

**Comment by stevenguh** [comment]
Thanks :) Merged
