### ISSUE TITLE
Why default to uppercase letters for buffer movement?

### ISSUE THREAD

**Issue by danielo515** [VSpaceCode/VSpaceCode#146]
Issue Type: <b>Feature Request</b>

Hello,
I was to move a buffer between tabs/groups and I noticed that all the motion letters (h,j,ik,l) should be typed uppercase. Why? There is no other binding under that submenu using then, then why not use the normal letters as default? It will be much simpler and faster to type.

Extension version: 0.8.5
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0

**Comment by stevenguh** [comment]
https://github.com/VSpaceCode/VSpaceCode/pull/61
It doesn't seems like we discussed it, but I agree that the upper case is part of my pain points as well.

**Comment by danielo515** [comment]
are you open to change them to normal letters (lowercase) then?

**Comment by stevenguh** [comment]
I am open it for sure :) PR is welcome.

@MarcoIeni Any thoughts?

**Comment by MarcoIeni** [comment]
I like the uppercase version for consistency with `<SPC w H/J/K/L>`, as discussed in the issue.
Anyway, Since `<SPC b h/j/k/l>` are free we can assign the same action to them. In this way people can use whatever they prefer and we don't break existing users muscle memory :)

**Comment by stevenguh** [comment]
Ah. I remember that now😅it was because it is similar to `SPC w H/J/K/L`.

> Anyway, Since <SPC b h/j/k/l> are free we can assign the same action to them. In this way people can use whatever they prefer and we don't break existing users muscle memory :)

That sounds good to me :)

**Comment by MarcoIeni** [comment]
Good, so Daniel, do you want to do a PR? :smile:

**Comment by danielo515** [comment]
@MarcoIeni done: https://github.com/VSpaceCode/VSpaceCode/pull/148
