### ISSUE TITLE
Python major mode

### ISSUE THREAD

**Issue by Muscaw** [VSpaceCode/VSpaceCode#149]
I'm creating this issue to link to the different PRs that will come for the python major mode.

I was wondering if it would make sense to document how the major modes of VSpaceCode map to the Spacemacs keybindings.
There are some features that can be mapped to some extension's commands, but it's not always possible.
I've seen that this discussion was already started in #108 .

Another point I would like to discuss is whether it makes sense to use free keybinding slots to map to new features provided by some extensions.

An example would be mapping `SPC m t x (or f)` to the action `Run the failed tests`.

@stevenguh @MarcoIeni what do you think?

**Comment by MarcoIeni** [comment]
> I'm creating this issue to link to the different PRs that will come for the python major mode.

Great! I linked this is issue in the original one.

> I was wondering if it would make sense to document how the major modes of VSpaceCode map to the Spacemacs keybindings.

Major mode is ducumented [here](https://vspacecode.github.io/docs/major-mode) and keybindings documentation is automatically generated and published [here](https://vspacecode.github.io/docs/default-keybindings). Do you feel like something is missing?

> Another point I would like to discuss is whether it makes sense to use free keybinding slots to map to new features provided by some extensions.

Sure! You can always open a new issue if you want to propose new key bindings ideas :)

> An example would be mapping `SPC m t x (or f)` to the action `Run the failed tests`.

Is this provided by an external extension or it is provided by the python layer? In the second case you can totally add it. In the first one share the link to this extension first, so we can evaluate it.

**Comment by stevenguh** [comment]
Thank you for getting the Python major mode bindings out. Is there any chance you can update our documentation like https://github.com/VSpaceCode/vspacecode.github.io/pull/24?

**Comment by Muscaw** [comment]
@stevenguh Sure

**Comment by Muscaw** [comment]
@stevenguh You can find the documentation update at https://github.com/VSpaceCode/vspacecode.github.io/pull/26
