### ISSUE TITLE
Horizontal window splits

### ISSUE THREAD

**Issue by cglwn** [VSpaceCode/VSpaceCode#15]
With grid layouts now available in VS Code, it would be great if the bindings for generating window splits and navigating them were added. The ones I know about and use regularly are:
- <kbd>SPC</kbd><kbd>w</kbd><kbd>-</kbd> for creating a horizontal split.
- <kbd>SPC</kbd><kbd>w</kbd><kbd>j</kbd> for moving to the split below.
- <kbd>SPC</kbd><kbd>w</kbd><kbd>k</kbd> for moving to the split above.

**Comment by StreakyCobra** [comment]
Hi,

Good idea. If you are interested to send a PR please do so. Otherwise we will have to wait on someone to do it. I may do it myself someday but I don't have time these days :-)

**Comment by cglwn** [comment]
Don't have the time right now (or VS Code extension programming experience) to do it myself either. I'll just leave this open if anyone else is interested in picking it up, or for when I'm free 😄.

**Comment by StreakyCobra** [comment]
This is fixed in 4aa2a101ab5a55d32929b6242d205579045cc695 by #17 :-)
