### ISSUE TITLE
Next / previous change?

### ISSUE THREAD

**Issue by max-sixty** [VSpaceCode/VSpaceCode#150]
Firstly thank you for the amazing extension — it's really the best of all worlds. I'm excited to see it develop.

## Solution

Would you be open to a PR of these as default for "Go to next / previous change"

```
"vspacecode.bindingOverrides": [
        {
            "keys": "g.p",
            "name": "Go to previous change",
            "type": "command",
            "command": "workbench.action.editor.nextChange",
        },
        {
            "keys": "g.n",
            "name": "Go to next change",
            "type": "command",
            "command": "workbench.action.editor.nextChange",
        }
    ]
```

## Alternatives

Totally fine to close this and people can paste this in themselves if they want it. Very much on board with gradually introducing defaults in they pick up a following.

**Comment by stevenguh** [comment]
Thank you for liking and using it :)
`<spc> g` is a more like "git/version control` in spacemacs. Since we are trying to emulate most of spacemacs, this binding might not fit that well. Maybe there is other place for this? What do you think? @MarcoIeni

**Comment by max-sixty** [comment]
Yes, good point. I was thinking to mirror `e.n` for next error. Very open to ideas for a better location.

**Comment by MarcoIeni** [comment]
I found `spc j c` to go to last change.

![image](https://user-images.githubusercontent.com/11428655/103436027-b768f580-4c17-11eb-904b-18d9434a3a6e.png)

Maybe the opposite could be `spc j C`.
Anyway I tried those actions and they are not doing anything in my IDE, don't know why.

**Comment by stevenguh** [comment]
> I found spc j c to go to last change.
> Maybe the opposite could be spc j C.

I like that, and it mapped closely to spacemacs.
`<spc> j c` will map to  `workbench.action.editor.previousChange`
`<spc> j C` will map to `workbench.action.editor.nextChange`

> Anyway I tried those actions and they are not doing anything in my IDE, don't know why.

Those works for me. Did you have changes in your buffer when you try them?

**Comment by MarcoIeni** [comment]
> Those works for me. Did you have changes in your buffer when you try them?

I tried this again, this time in a markdown file within a repository versioned with git and it works.

So, great! max-sixty do you want to submit a PR? :smile:

**Comment by max-sixty** [comment]
Yes for sure — I have an easy-but-not-instant process for getting OSS approval — give me a couple of days.
