### ISSUE TITLE
Approach to discover keybindings?

### ISSUE THREAD

**Issue by max-sixty** [VSpaceCode/VSpaceCode#151]
## Problem

Currently it's not that easy to discover the keybindings. I occasionally find myself squinting and trying various menus to see if something exists.

(Also possible I'm missing something that already exists — please correct me if so!)

## Solution & Alternatives

I'm not sure what the best design would be. Here are a few ideas, in approximate & arguable order of preference:
- Could they appear in the "Show all commands" next to the regular keybindings? Not sure whether this is technically possible.
- Could there be a similar-but-different "Show all commands" prompt that would only show the commands available within vspacecode, and allow autocomplete?
- Could there be a command to jump to a JSON setting page, so they could be searched over manually?

**Comment by stevenguh** [comment]
Related: https://github.com/VSpaceCode/vscode-which-key/issues/12#issuecomment-744208308

We don't have that functionality yet. The current thought is to implement something like `<spc> ?`, so a user can search through current bindings. Does that address your pain point?

**Comment by max-sixty** [comment]
Ah, great, sorry I missed that. Thanks, closing.

**Comment by stevenguh** [comment]
All good :)
