### ISSUE TITLE
Clojure major mode

### ISSUE THREAD

**Issue by jr0cket** [VSpaceCode/VSpaceCode#153]
## Problem
Calva is the defacto extention for Clojure development using VSCode and currently does not have major mode support in VSpacecode

* [Calva extension on VS Code marketplace](https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva)
* [Calva code repository](https://github.com/BetterThanTomorrow/calva)

## Solution
Add key bindings in VSpaceCode to support the features provided by the Calva extension

https://calva.io/ documents the features of the extension, along with command names used.

Key binding design document
https://gist.github.com/889cd50a59f601698b7f83e39c1e4b0b

Todo
- [x] Add VSpaceCode key bindings to +Major mode section of the packages.json file - #154 
- [x] Add Clojure major mode to https://vspacecode.github.io/docs/major-mode - https://github.com/VSpaceCode/vspacecode.github.io/pull/24
- [ ] add key binding documentation (add as a child page of above, as there are a large number of key bindings - create table for each sub-menu of key bindings)

Related discussions in #98 , #108 and #149 
References #14

**Comment by MarcoIeni** [comment]
Is [this](https://vspacecode.github.io/docs/default-keybindings) what you are referring to in point 3? Because that's created automatically at every tag thanks to [this](https://github.com/VSpaceCode/VSpaceCode/blob/master/.github/workflows/keybindings.yml) action :)

**Comment by stevenguh** [comment]
> add key binding documentation (add as a child page of above, as there are a large number of key bindings - create table for each sub-menu of key bindings)

We don't have infrastructure for this yet if I understand correctly (a sub page per major mode). We only have the a monolith default binding pages.

**Comment by stevenguh** [comment]
I will close this as we don't have to infra for separate major mode page, and the monolith default binding page will update once we release.

**Comment by jr0cket** [comment]
> Is [this](https://vspacecode.github.io/docs/default-keybindings) what you are referring to in point 3? Because that's created automatically at every tag thanks to [this](https://github.com/VSpaceCode/VSpaceCode/blob/master/.github/workflows/keybindings.yml) action :)

The GitHub workflow adds the top level menu for Major modes to the [default keybindings documentation](https://vspacecode.github.io/docs/default-keybindings/) if I understand correctly.  This should be enough for basic awareness.

The https://github.com/VSpaceCode/vspacecode.github.io/pull/24 pull request adds Clojure to the Major mode section of the documentation and includes links to an external [install guide](https://practicalli.github.io/clojure/clojure-editors/editor-install-guides/vspacecode-calva.html) and [user guide](https://practicalli.github.io/clojure/clojure-editors/editor-user-guides/vspacecode-calva.html) in the Practicalli collection of Clojure aware editors.

Together this does provide all the documentation someone may need to use the new Clojure key bindings.  The key bindings should also be familiar to those coming from Spacemacs or Emacs Doom and fairly recognizable to existing Calva users.

I updated the original ticket tasks to reflect what has been done.

Thank you for all your help.

**Comment by MarcoIeni** [comment]
Thank you for your awesome contribution 🚀
