### ISSUE TITLE
Ruby major mode

### ISSUE THREAD

**Issue by mdudzinski** [VSpaceCode/VSpaceCode#158]
## Problem

There are no keybindings for Ruby major mode. 

## Solution

The basic subset can be based on the built-in editor commands that are provided by [Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) and/or [Ruby Solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph) extensions:

* code navigation
* code refactoring
* formatting

## Alternatives

Open for suggestions.

## Additional context

N/A

**Comment by stevenguh** [comment]
Closed since all the PRs are merged. Thank you for contributing :)
