### ISSUE TITLE
Unify format commands

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/VSpaceCode#160]
## Problem
Our format keys are not consistent with spacemacs (in light of the current PRs). We have
1. `<spc> f =` binds to `editor.action.formatDocument`
2. `<spc> j =` binds to `editor.action.format`
3. `<spc> m =` menu in different major modes for go, python, and ruby (in master and in PR)
    - `<spc> m = = ` binds to `editor.action.formatDocument`
    - `<spc> m = d` binds to `editor.action.formatDocument`
    - `<spc> m = m` binds to `editor.action.formatChanges`
    - `<spc> m = s` binds to `editor.action.formatSelection`
    - `<spc> m = S` binds to `editor.action.formatSelection.multiple`

As a reference, spacemacs use the [following convention](https://develop.spacemacs.org/doc/CONVENTIONS.html#code-formatting):
Key binding | Description
-- | --
m = = | format thing under point
m = b | format current buffer
m = f | format current function

## Solution
Idea is to unify the formatting bindings as much to the language of spacemacs.

1. `<spc> f =` binds to `editor.action.formatDocument`
    Options:
    - Remove it since file (`f`) is not related to the current buffer
    - Move it to buffer (`b`) and rename it to format buffer but it would be kind of duplicate of `<spc> j =` and the major modes

2. `<spc> j =` binds to `editor.action.format`
    - No change since it mapped closed to [spacemacs](https://develop.spacemacs.org/doc/DOCUMENTATION.html#joining-and-splitting)' format the marked region or entire buffer

3. `<spc> m =` menu in different major modes for go, python, and ruby (in master and in PR)
    This followings would apply to all the major modes that has it.
    - `<spc> m = =` binds to `editor.action.formatDocument`
        - Change to the same binding in `<spc> j =`
    - `<spc> m = d` binds to `editor.action.formatDocument`
        - Change it to `<spc> m = b` as it is formatting the buffer
    - `<spc> m = m` binds to `editor.action.formatChanges`
        - Since we used `c` in `<spc> j c` to jump to last change, we should change this to `<spc> m = c`
    - `<spc> m = s` binds to `editor.action.formatSelection`
        - This is effective the same as `<spc> j =`, so we can either keep it or remove it.
    - `<spc> m = S` binds to `editor.action.formatSelection.multiple`
       - I don't know what this does exactly. I am assuming if there is multiple format providers, it will give you a menu? I would change the name to "Format selection with providers" if that's the case. There's also another similar command `editor.action.formatDocument.multiple`, I would add that as `<spc> m = B`

## Additional context

@MarcoIeni  Let me know what do you think?

Blocker PR :
- [ ] https://github.com/VSpaceCode/VSpaceCode/pull/157
- [ ] https://github.com/VSpaceCode/VSpaceCode/pull/159

**Comment by MarcoIeni** [comment]
Thank you for the accurate review Steven!

# 1

- [ ] Let's remove `spc f =`, it's useless.
- [ ] Also we should always use `editor.action.format` over `editor.action.formatDocument`, because it works as expected in visual mode.

Do you agree?

# 2

ok, no action required then.

# 3

> * `<spc> m = =` binds to `editor.action.formatDocument`
>   
>   * Change to the same binding in `<spc> j =`

Agree: as I said, `editor.action.format` everywhere!

> * `<spc> m = d` binds to `editor.action.formatDocument`
>   
>   * Change it to `<spc> m = b` as it is formatting the buffer

For me it's fine but I don't find it useful..why you might want to use this instead of `<spc> m = =`?
I would just remove this.

> * `<spc> m = m` binds to `editor.action.formatChanges`
>   
>   * Since we used `c` in `<spc> j c` to jump to last change, we should change this to `<spc> m = c`

Agree!

> * `<spc> m = s` binds to `editor.action.formatSelection`
>   
>   * This is effective the same as `<spc> j =`, so we can either keep it or remove it.

Let's remove it!

> * `<spc> m = S` binds to `editor.action.formatSelection.multiple`

Let's discuss this later.

**Comment by stevenguh** [comment]
> - [ ] Let's remove `spc f =`, it's useless.
> - [ ] Also we should always use `editor.action.format` over `editor.action.formatDocument`, because it works as expected in visual mode.
> 
> Do you agree?

We probably shouldn't out right remove it, because I just remembered that not all formatter will work `editor.action.format`. Some will only work with `editor.action.formatDocument`. I also took a look at the buffer menu (`b`), buffer menus is managing the buffer and not the content in it so it doesn't make sense there as well. I found `<spc> j +` seems to match our usage of format the whole doc well?

> > * `<spc> m = d` binds to `editor.action.formatDocument`
> >   
> >   * Change it to `<spc> m = b` as it is formatting the buffer
> 
> For me it's fine but I don't find it useful..why you might want to use this instead of `<spc> m = =`?
> I would just remove this.

Base on the formatting issue I just remembered and mentioned above, We probably should move to `<spc> m = b` to stay consistent to spacemacs convention while also providing function.

> > * `<spc> m = s` binds to `editor.action.formatSelection`
> >   
> >   * This is effective the same as `<spc> j =`, so we can either keep it or remove it.
> 
> Let's remove it!
> 
> > * `<spc> m = S` binds to `editor.action.formatSelection.multiple`
> 
> Let's discuss this later.

Let's figure what `editor.action.formatSelection.multiple` and `editor.action.formatDocument.multiple` do. It kind nice  sense to have the symmetry of 
- `<spc> m = b`, and `<spc> m = B`
- `<spc> m = s`, and `<spc> m = S`

**Comment by MarcoIeni** [comment]
> We probably shouldn't out right remove it, because I just remembered that not all formatter will work `editor.action.format`.

oh, ok!

- [ ] move `<spc> f =` to `<spc> b =`
- [ ] add `<spc> j +` to `editor.action.formatDocument`
- [ ] move `<spc> m = d` to `<spc> m = b`

> Let's figure what `editor.action.formatSelection.multiple` and `editor.action.formatDocument.multiple` do. It kind nice sense to have the symmetry of
> 
> * `<spc> m = b`, and `<spc> m = B`
> * `<spc> m = s`, and `<spc> m = S`

- [ ] check if these actions are useful. If yes, add them to `<spc> m = S` and `<spc> m = B`

**Comment by stevenguh** [comment]
> - [ ] move `<spc> f =` to `<spc> b =`
> - [ ] add `<spc> j +` to `editor.action.formatDocument`

`<spc> b` is managing the buffer and not the content, so wouldn't `<spc> j +` be suffice? 

- [x] move `<spc> m = d` to `<spc> m = b`

> > Let's figure what `editor.action.formatSelection.multiple` and `editor.action.formatDocument.multiple` do. It kind nice sense to have the symmetry of
> > 
> > * `<spc> m = b`, and `<spc> m = B`
> > * `<spc> m = s`, and `<spc> m = S`
> 
> - [ ] check if these actions are useful. If yes, add them to `<spc> m = S` and `<spc> m = B`

Makes sense

**Comment by stevenguh** [comment]
> > Let's figure what `editor.action.formatSelection.multiple` and `editor.action.formatDocument.multiple` do. It kind nice sense to have the symmetry of
> > 
> > * `<spc> m = b`, and `<spc> m = B`
> > * `<spc> m = s`, and `<spc> m = S`
> 
> - [ ] check if these actions are useful. If yes, add them to `<spc> m = S` and `<spc> m = B`

Those `editor.action.format*.multiple` commands allow user to select a formatter if there is more than one formatter register for the file type. For example, you can try this by installing prettier extension.

![image](https://user-images.githubusercontent.com/3455662/104536868-bc418800-55cd-11eb-879c-de27870b5d9a.png)

I am proposing:
- [ ] Move `<spc> f =` to `<spc> j +`
- [ ] Binds `<spc> m = =` to `editor.action.format`
- [ ] Binds `<spc> m = b` to `editor.action.formatDocument`
- [ ] Binds `<spc> m = B` to `editor.action.formatDocument.multiple`
- [ ] Binds `<spc> m = c` to `editor.action.formatChanges`
- [ ] Binds `<spc> m = s` to `editor.action.formatSelection`
- [ ] Binds `<spc> m = S` to `editor.action.formatSelection.multiple`

For some major modes, plug-in that offers format at point will be used to replace `<spc> m = =` like clojure.

**Comment by MarcoIeni** [comment]
Yes, I agree. I opened #161 and #162 to track these actions!
I am closing this. If you feel like you want to discuss something else feel free to open this again.

**Comment by stevenguh** [comment]
Thanks :)
