### ISSUE TITLE
Unify major mode commands

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#162]
## Problem

We want major modes to have similar key bindings in order to favor muscle memory.

## Solution

every major mode should have the following key bindings:

> * Bind `<spc> m = =` to `editor.action.format`
> * Bind `<spc> m = b` to `editor.action.formatDocument`
> * Bind `<spc> m = B` to `editor.action.formatDocument.multiple`
> * Bind `<spc> m = c` to `editor.action.formatChanges`
> * Bind `<spc> m = s` to `editor.action.formatSelection`
> * Bind `<spc> m = S` to `editor.action.formatSelection.multiple`

We should:

- [ ] add this key bindings to every major mode that is available at the moment
- [ ] write these key bindings in the contributing guidelines (or somewhere else?)

## Additional context

Issue opened from [this](https://github.com/VSpaceCode/VSpaceCode/issues/160#issuecomment-759887333) comment.

**Comment by stevenguh** [comment]
> - add this key bindings to every major mode that is available at the moment

 #168 Changed all the existing bindings except Clojure since it has its own formatting bindings that's not standard.

> - write these key bindings in the contributing guidelines (or somewhere else?)

https://github.com/VSpaceCode/vspacecode.github.io/pull/29 Updated the document to have a convention page like spacemacs.
