### ISSUE TITLE
[Question] Keybinding to leave file tree?

### ISSUE THREAD

**Issue by piazzatron** [VSpaceCode/VSpaceCode#163]
I've browsed the documentation for this but haven't seen it answered anywhere - is there a keybinding to lose focus on the file tree and jump back to your frames? 

I see there are multiple bindings to enter the file tree (`spc f t`, etc), but once the file tree has focus, I'm not sure how to make it lose focus without selecting a file. This is the one issue consistently causing me to use my mouse. 

Thanks for your help! Huge fan of this plugin.

**Comment by stevenguh** [comment]
Related to https://github.com/VSpaceCode/VSpaceCode/issues/85. It is an area that's missing right off the box.

1. You can add the config in https://github.com/VSpaceCode/VSpaceCode/issues/85#issue-676353520 to keybindings.json. That will allow you to use the `<spc>` in the sidebar, and doing `<spc> f t` should collapse the sidebar.
2. I personally use https://vspacecode.github.io/docs/bonus#quick-window-navigation to navigate focus of vscode.

**Comment by piazzatron** [comment]
@stevenguh the config from #85 worked perfectly! And I didn't know about quick-window-navigation; this is great, I'm switching to this as my primary method to navigate focus.

Thanks for the quick response. Closing this one.
