### ISSUE TITLE
next error is both under error (correct) and under comments. Why?

### ISSUE THREAD

**Issue by danielo515** [VSpaceCode/VSpaceCode#165]
Take a look at this screenshot:

![image](https://user-images.githubusercontent.com/2270425/105068540-56e41000-5a81-11eb-84b2-dbcbdae79b24.png)

Why are the navigate to next error bindings under the comments namespace? Doesn't make sense to me.

**Comment by stevenguh** [comment]
I think these are based on the spacmacs current bindings.
![image](https://user-images.githubusercontent.com/3455662/105083259-89721680-5a49-11eb-83e8-eccb180eac99.png)

**Comment by MarcoIeni** [comment]
Because `c` in spacemacs is `Compile/Comments`

**Comment by danielo515** [comment]
> Because `c` in spacemacs is `Compile/Comments`.
> Should we rename it as well?

But that is a totally different context. It will show you compile errors, which makes sense in the context of compile, but doesn't make any sense to navigate errors on the comments.

**Comment by stevenguh** [comment]
Those are the closest comment that we have. In some cases, spacemacs' behavior can be similar to what we have. Do you have any recommendation?

> Should we rename it as well?

Since vscode doesn't really have the concept of compile, the most similar one is build. Should we add `workbench.action.tasks.build` as `<spc> c c` so we can rename the `<spc> c` from `+Comment` to `+Compile/Comment`?

**Comment by MarcoIeni** [comment]
I like your idea, I created a PR. This key binding was already present as `<spc> p c` by the way

**Comment by danielo515** [comment]
Is it really that important to keep as close as possible to spacemacs? There are other very similar approaches lake spacevim, doom-emacs, space-vim (yes, with a dash). I don't see a reason why this should try to follow the steps of any of those. Maybe it can try to make it's own way adding what makes sense on for vscode users?
That said, I like the idea of adding tasks to some place, but selecting one tasks specifically seems to be to narrowed down?

**Comment by MarcoIeni** [comment]
> Is it really that important to keep as close as possible to spacemacs?

Yes, spacemacs key bindings take precedence. That's the whole point of this project, sorry. 😅

> Maybe it can try to make it's own way adding what makes sense on for vscode users?

Personally, my number 1 priority is to be able to switch between spacemacs, vscode and intellij without any problems. This is achieved by using the same key bindings of spacemacs. There will never be one set of key bindings that fit for everyone.

Having one "source of truth" (spacemacs in this case) makes it very easy for us to work on this repo without incurring into personal preference (most of the times).
If somebody wants to create a brand new set of key bindings they can build it on top of [which key](https://github.com/VSpaceCode/vscode-which-key), which is what this repo does.

I hope I explained my motivations clearly, I am sorry if you don't like some of the key bindings and I hope that which key customization options are enough to fit your needs.

**Comment by stevenguh** [comment]
>Personally, my number 1 priority is to be able to switch between spacemacs, vscode and intellij without any problems. This is achieved by using the same key bindings of spacemacs. There will never be one set of key bindings that fit for everyone.
>
> Having one "source of truth" (spacemacs in this case) makes it very easy for us to work on this repo without incurring into personal preference (most of the times).

Agree and I would say on the similar line. However, we do have some bindings that are specific to vscode. Priority is definitely providing similar bindings as spacemacs, then we can discuss/consider what vscode specific key we can/should add.

> If somebody wants to create a brand new set of key bindings they can build it on top of which key, which is what this repo does.

The customization we have should be a fairly good escape hatch. https://vspacecode.github.io/docs/menu-customization

**Comment by stevenguh** [comment]
I merged the PR by Marco which closed this issue. Feel free to open the issue if you think there's more to discuss about the philosophy. We are certainly open to ideas about vscode focused bindings but we also want to retain bindings in spacemacs first.

**Comment by danielo515** [comment]
> I merged the PR by Marco which closed this issue. Feel free to open the issue if you think there's more to discuss about the philosophy. We are certainly open to ideas about vscode focused bindings but we also want to retain bindings in spacemacs first.

I completely understand your point.
Thanks.
