### ISSUE TITLE
Will you consider adding a command to checkout branch?

### ISSUE THREAD

**Issue by danielo515** [VSpaceCode/VSpaceCode#171]
## Problem

I can't checkout directly from vspacecode

## Solution

Can we add a command to checkout to a branch? It should just trigger the checkout command of vscode

## Alternatives

Just use the normal VSC palette

## Additional context

I am open to make a PR, but I would need to know where to put it.

**Comment by stevenguh** [comment]
Would this be similar to `<spc> g m b`?

**Comment by danielo515** [comment]
> Would this be similar to `<spc> g m b`?

Yes, but using the vscode command instead of going through magit.

**Comment by stevenguh** [comment]
Is there any reason you like the vscode command instead?

I would say that it might be confusing to have multiple git extensions interacting (built-in, edamagit, and potentially like me gitlens). Good thing about our overrides is that everyone can customize their favorite bindings and can share with the community in https://github.com/VSpaceCode/community-configs

Although there's a lot to be desire from the edamagit dispatch, it matches the experience of magit in spacemacs closely.

In the future, I am thinking how can we do something similar to spacemacs layers, so we may able to provide more choices on the bindings. For example, a user might not want to use edamagit, and want to use gitlens for example. They can easily switch to different bindings. Extended that further, a user might able to use a community binding easily. This is not here today, but I am thinking how we can do this within the vscode system.

**Comment by stevenguh** [comment]
> I am not sure about this, but I think it was not possible to just override one submenu? I have to override the entire magit one?

The override is fairly flexible. You can add/change/remove any item. See https://vspacecode.github.io/docs/menu-customization

The following override can change the blame to branch or add to the menu if `b` doesn't exist.
```json
{
  "vspacecode.bindingOverrides": [
    {
      "keys": "g.b",
      "name": "Branch",
      "type": "command",
      "command":"command.to.branch",
    }
  ]
}
```

**Comment by danielo515** [comment]
That is awesome! Thanks
