### ISSUE TITLE
Can I close the magit help window with keyboard?

### ISSUE THREAD

**Issue by ilyagr** [VSpaceCode/VSpaceCode#173]
Let's say I open magit status with `<Space> g s`, and then press `?` to get help. I'd like there to be a way to close the help window without changing anything else. 

I'd also like a way to do this after pressing `<Space> g s ? q`. (Or, the help window could close automatically after I closed the corresponding Magit window)

Is there an easy way to do this with the keyboard that I missed? The closest I've found is the "Close all other windows" command, but if my window was already split in two, it closes everything in the other pane (and not just the help window).

In Emacs, I think I could do this with `C-g`.

Thank you!

**Comment by stevenguh** [comment]
> Let's say I open magit status with <Space> g s, and then press ? to get help. I'd like there to be a way to close the help window without changing anything else.

<kbd>q</kbd> works for me for all the magit window.

> (Or, the help window could close automatically after I closed the corresponding Magit window)

I kind wish for that as well especially magit dispatch is just a help window. That however is an upstream issue with edamagit. Would you like to open an issue in edamagit repo?

> Is there an easy way to do this with the keyboard that I missed? The closest I've found is the "Close all other windows" command, but if my window was already split in two, it closes everything in the other pane (and not just the help window).

I don't think there is a command to close all magit editor (buffer). That could be an upstream feature request to edamagit as well. One related commands I use to collapse all splits is <kbd>SPC</kbd><kbd>w</kbd><kbd>z</kbd>.

**Comment by ilyagr** [comment]
Thanks for looking at this!

> q works for me for all the magit window.

I think I didn't explain what happens precisely enough. Now that I understand it better myself, I think it is a bug rather than a feature request. See https://github.com/VSpaceCode/VSpaceCode/issues/174. I think fixing that bug will fix this issue as well (so feel free to close this).

It is important that, when starting out, the VS Code window has 2 panes, with files open in both of them. Then,  press `<Space> g s ? q`. There is no good way to close the help window.

**Comment by ilyagr** [comment]
And never mind. This is indeed an issue with Magit, not VSpaceCode. Sorry to bother.
