### ISSUE TITLE
Opening and closing Magit can move you to the other pane

### ISSUE THREAD

**Issue by ilyagr** [VSpaceCode/VSpaceCode#174]
## Bug description

When using VS Code with a window split in two panes, using Magit and quitting moves you to the other pane.

## To Reproduce

1. Open files in 2 panes in VS Code. Make sure you are in a git repository.
2. Press `<Space> g s q`, thus opening and closing Magit.

## Expected behavior
You are back in the same pane you started with.

## Actual result
You are in the other pane than the one you started with.

## Additional context

This becomes especially annoying if you also open a help window. See https://github.com/VSpaceCode/VSpaceCode/issues/173 for the way it got me confused.

**Comment by ilyagr** [comment]
I checked, this is an issue with Magit, not VSpaceCode. I filed it as https://github.com/kahole/edamagit/issues/106.

I'll let you decide whether to keep this open or closed.

**Comment by stevenguh** [comment]
I am going to close this, since there's not much we can do in this repo. Feel free to open an issue or discuss if there anything we can do in this repo.
