### ISSUE TITLE
How to bind <backspace> key to some command?

### ISSUE THREAD

**Issue by origamidance** [VSpaceCode/VSpaceCode#180]

**Comment by stevenguh** [comment]
See https://vspacecode.github.io/docs/whichkey/extra#use-non-character-keys. Free feel to open an issue to update the doc if it isn't clear.

Basically, you will need to add the following json to you user's keybindings.json
```json
{
    "key": "backspace",
    "command": "whichkey.triggerKey",
    "args": "BS",
    "when": "whichkeyVisible"
}
```

And use "BS" as the key in the overrides in your settings.

```
"vspacecode.bindingOverrides": [
    {
        "keys": "BS",
        "name": "You Cmd",
        "type": "command",
        "command": "replace.with.your.command",
    }
] 
```

**Comment by origamidance** [comment]
Thank you very much! I didn't realize it's in the Whichkey section. Now it's clear to me.
