### ISSUE TITLE
"Failed to install" message shown on install attempt with no details

### ISSUE THREAD

**Issue by idrozd** [VSpaceCode/VSpaceCode#189]
## Bug description

"Failed to install" message shown on install attempt with no details
Manually downloaded extension fails quietly

## Screenshots

![image](https://user-images.githubusercontent.com/870478/114985462-82697180-9e9b-11eb-87f8-0dc68a45e723.png)

## Additional context

Was not able to find a way to check VSCode's error log or any source of additional info
Suggestions?

## System information

macOS Mojave 10.14.4

**Comment by stevenguh** [comment]
Have you tried https://github.com/microsoft/vscode/issues/84937. Maybe this is an DNS issue?

**Comment by idrozd** [comment]
D'oh, I had 2018 version of VSCode, 
too much used to auto-update 

Sorry for bothering
