### ISSUE TITLE
Cancel transient mode in some entry

### ISSUE THREAD

**Issue by Jacfger** [VSpaceCode/VSpaceCode#190]
## Problem
```
        {
            "keys": "n",
            "name": "Navigate",
            "type": "transient",
            "bindings": [
                {
                    "key": "u",
                    "name": "Half page up",
                    "type": "command",
                    "command": "vim.remap",
                    "args": {
                        "after": ["<C-u>"]
                    }
                },
                {
                    "key": "d",
                    "name": "Half page down",
                    "type": "command",
                    "command": "vim.remap",
                    "args": {
                        "after": ["<C-d>"]
                    }
                }
            ]
        },
        {
            "keys": "n.s",
            "name": "Search",
            "type": "command",
            "command": "vim.remap",
            "args": {
                "after": ["<leader>", "<leader>", "s"]
            }
        }
```

I had set up my key bindings like this so that when I'm done scrolling, I can simply do easy motion in vscode vim and find the string that I want to go to. However, since "n" is set as "transient", it wouldn't close the menu and continue the taking the buffer.

e.g. n->s will enter to easy motion mode. Let say we want to search the string "easy", it would become things like searching "asy" instead because the character "e" would be eaten up by the input bar and generate error (because there's no such binding). Then, it exit the menu and I'll be typing to the easy motion input buffer instead of to the menu. So in this case I'll be searching "asy" instead of what I wanted "easy".

## Solution

Is there any way to disable the transient menu when some key entry is pressed? Like in this case, typing "s" would cancel the transient mode and exit the menu

## Alternatives

I can't.

## Additional context

No

**Comment by stevenguh** [comment]
This is in a refactoring that I've been doing on the which-key side which breaks out transient to its own command to support configuration on an item to be an "exit" command. I just haven't have time flush that out. I should have more time to flush that out next month.

**Comment by Jacfger** [comment]
Ahhh, ic this is extremely nice to hear! thank you!
