### ISSUE TITLE
SPC SPC Does Not Open Command Palette

### ISSUE THREAD

**Issue by li-xinyang** [VSpaceCode/VSpaceCode#2]
![bug](https://cloud.githubusercontent.com/assets/3349406/26116119/9919d088-3a94-11e7-959f-559f2c9af79e.gif)

SPC SPC won't open Command Palette when the cursor is on text, but it is working when it is on a blank line.

I think this is caused by CodeVim.

**Comment by StreakyCobra** [comment]
Oh I forgot, you have to set `"vim.leader": " ",` in your settings to have it to work. I think it's a needed workaround. Can you confirm it works?

**Comment by li-xinyang** [comment]
The bug persists when setting the `"vim.leader"` to `" "` or `"<space>"` . Do you have similar problem?

**Comment by StreakyCobra** [comment]
Ok, my bad. No I haven't met this problem yet.

I tried right now to create a tsx file with this content:

```tsx
var App = {};

export default App;
```

But even with the cursor being on `App` like you I can trigger the command.

Maybe one extension you have is conflicting?

**Comment by li-xinyang** [comment]
I have disabled all the extension except `vscodevim` but the error persists.

![a](https://cloud.githubusercontent.com/assets/3349406/26158437/74f0def8-3b4e-11e7-9822-80c948abdc99.gif)


However, holding `SPC` does trigger the command.

![b](https://cloud.githubusercontent.com/assets/3349406/26158446/7b3e6d20-3b4e-11e7-84ab-cdc46a7eae4e.gif)

**Comment by StreakyCobra** [comment]
Weird, maybe a OS X specificity?

**Comment by li-xinyang** [comment]
Possible, but I do not have any OS to test except macOS at this moment.

**Comment by StreakyCobra** [comment]
And I don't have a MacOS for testing :joy:

**Comment by li-xinyang** [comment]
I found a deceleration of `vim.leader` inside my config file. The issue is solved after remove of the duplicated key.
