### ISSUE TITLE
Way to bring up prompt for documentation (a la Pycharm)

### ISSUE THREAD

**Issue by IanQS** [VSpaceCode/VSpaceCode#209]
## Problem

Pycharm has some capability where, when you press CTRL/CMD-p, it brings up the documentation for the function (both library and implementation functions). The use case would be to manually pull up the function stub after filling in the args (I've manually deleted all the arguments to make it pop up again). I did a search through the [VSpaceCode default keybindings](https://vspacecode.github.io/docs/default-keybindings) but none of what I found seemed like what I wanted.

## Solution

keybindings to bring up prompt

## Additional context

Sort of along the lines of the following. I moved away from the function, "forgot" the arguments and their signatures, but was able to pull it up with some CTRL/CMD-p. 

![second](https://user-images.githubusercontent.com/6968573/124551397-e2aae800-dde6-11eb-917a-53a7ed9d2904.png)

I'd really appreciate this as this change would pretty much move me away from Pycharm

**Comment by stevenguh** [comment]
This is not related to VSpaceCode, but I think you can try adding the following to your `keybindings.json`
```
	{
		"key": "cmd+p",
		"command": "editor.action.triggerParameterHints",
		"when": "editorHasSignatureHelpProvider && editorTextFocus"
	},
```

**Comment by IanQS** [comment]
Ahh, crap. Sorry, I assumed that it was a feature consistent throughout all the layers. I didn't think to look in `keybindings.json`. Thank you so so much for your help
