### ISSUE TITLE
Paredit/Smartparens Integration

### ISSUE THREAD

**Issue by Immortalin** [VSpaceCode/VSpaceCode#21]
https://marketplace.visualstudio.com/items?itemName=cospaia.paredit-revived

**Comment by StreakyCobra** [comment]
I am not coding in Lisp so I do not have a personal interest to integrate this, but if someone is willing to do it the idea would be to put all the mappings concerning this extension in its own JSON file, like `extension/paredit.json`. The README could then be updated to explain than this file can be merged into the VSCode config and that it provides spacemacs bindings for this extension.

**Comment by Immortalin** [comment]
Update link: https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva

**Comment by StreakyCobra** [comment]
If anyone is interested and want to make a PR for paredit/smartparens/calva that will be welcome. In the meantime I'm closing this issue :)
