### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by max-sixty** [VSpaceCode/VSpaceCode#213]
Quick message to say thanks for this superb extension! 

I appreciated the UI of spacemacs even as I came to prefer VSCode, and this is really the best of both worlds. I've also started splitting myself between Mac & Linux again, and having comparable shortcuts between them is really nice.

I left a review. I'd be happy to contribute to a GH Sponsors, even if the initial number of people might be smaller than you deserve.

**Comment by The-Compiler** [comment]
Totally agree! Discovering this extension (plus edamagit) made VS Code from "hm, so many things seem nicer than in Spacemacs / DOOM Emacs but I just can't live without the space menus" to "ok omg I'm going to switch in a heartbeat". I wouldn't look back! I'd totally add a couple of dollars to a GitHub Sponsors campaign too, I try to do so with all software I use regularly.

**Comment by MarcoIeni** [comment]
Thank you for the appreciation! :)

**Comment by MarcoIeni** [comment]
I talked to Steven and we decided to not add a GH sponsor badge in this repo for now, mainly because the project has contributions from many people so it would never be fair unless there’s an organization structure to control the funds.
In addition, this project doesn’t have any spending costs e.g. severs or cloud providers.

I am closing this. Again, thank you! :)

**Comment by stevenguh** [comment]
Sorry I have been putting this off in replying. Thank you @MarcoIeni for reaching out. I am just glad people find it useful and liking it :)

**Comment by alexn-s** [comment]
i really appreciate the work you did and love this extensions.
dont know how i used vscode before.

if you decide to add sponsoring options in the future i would be happy to take part.
i recommended your extension to basically all of my friends. cant understand why it has not more downloads,

i wish you the best 💖
