### ISSUE TITLE
h j k l navigation when the key is continuously pressed.

### ISSUE THREAD

**Issue by abhijeetsrivastava** [VSpaceCode/VSpaceCode#216]
## Problem

When doing navigation via arrow keys, it will move the cursor when is continuously pressed, same with h j k l in spacemacs.
But when using VSpaceCode h j k l just moves one position and stops. 

## Solution
h j k l should move the cursor continuously similar to spacemacs.

**Comment by stevenguh** [comment]
Are you using mac? You probably need to config `ApplePressAndHoldEnabled`. See https://github.com/VSCodeVim/Vim#mac

**Comment by abhijeetsrivastava** [comment]
Thanks, it works.
