### ISSUE TITLE
Leader

### ISSUE THREAD

**Issue by mcaple** [VSpaceCode/VSpaceCode#217]
## Problem

This was a merger of two projects but [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) allowed for the leader to be changed with something like

    "vim.leader": "<space>",
    "vim.visualModeKeyBindings": [
        {
            "before": ["<leader>", "<space>"],
            "commands": ["workbench.action.showCommands"]
        },

the default extension is not configured this way. I would like to use ctl+\<space\> as my leader at certain times as well as \<space\> at other times. I would toggle the leader using the extension Settings Cycler. 

## Solution

Allow for vim.leader to be configured

**Comment by stevenguh** [comment]
I am not sure I fully understand. My understanding is that you are using the VSpaceCode extension.

> I would like to use ctl+<space> as my leader at certain times as well as <space> at other times. I would toggle the leader using the extension Settings Cycler.

How do you set up the activation of the menu? Can you elaborate a little bit more this?

> Allow for vim.leader to be configured

In the setting up the extension, `SPC` key that activates the which-key menu is separate from `vim.leader` key.

**Comment by mcaple** [comment]
Sorry @stevenguh just came across your excellent extension and realise I just need to have the following for what I need. The vim.leader option sent me down the wrong path as I saw it mentioned in the config for vscode-vim. Basically I will toggle between \<space\> and \<C-space\>, so nothing for you to do and you can close.

"vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "\<C-space\>"
            ],
            "commands": [
                "vspacecode.space"
            ]
        },
