### ISSUE TITLE
Can't use '.' in override commands

### ISSUE THREAD

**Issue by PatrickWulfe** [VSpaceCode/VSpaceCode#224]
## Bug description

{
      "keys": ".",
      "name": "QuickFix",
      "icon": "lightbulb-autofix",
      "type": "command",
      "command": "keyboard-quickfix.openQuickFix"
},

In the binding overrides, that won't work, yet if I replace the '.' with any other character it will work.  I was also trying to override SPC x . using "x.." which doesn't work either.

**Comment by stevenguh** [comment]
This is kind of expected because we `.` as a separator. Try the alternate syntax for keys.

For example:
```json
{
    "keys": ["."],
    "name": "QuickFix",
    "icon": "lightbulb-autofix",
    "type": "command",
    "command": "keyboard-quickfix.openQuickFix"
}
```
