### ISSUE TITLE
How can I change from interal terminal to (some) window?

### ISSUE THREAD

**Issue by fkromer** [VSpaceCode/VSpaceCode#227]
## Problem

I don't know of any mouse-free way to navigate from the internal terminal to the window or one of the windows in case several are open. I'm looking for some efficient inverse of `Space '`. Is there some way to do this w.o. the mouse?

**Comment by stevenguh** [comment]
Related: https://github.com/VSpaceCode/VSpaceCode/issues/85#issuecomment-859381836

We don't yet have an out-of-the-box way to navigate out of terminal focus. There are two things you can do:
1. Use the [Quick Window Navigation](https://vspacecode.github.io/docs/bonus#quick-window-navigation)
2. Add the `Shift+Space` as shortcut as mentioned in https://github.com/VSpaceCode/VSpaceCode/issues/85#issuecomment-859381836

**Comment by fkromer** [comment]
Thanks @stevenguh
