### ISSUE TITLE
open-link in Text related commands (start with `x`)

### ISSUE THREAD

**Issue by o8vm** [VSpaceCode/VSpaceCode#235]
## Problem

The text manipulation commands in spacemacs have a binding that opens a link with `SPC x o`. I've been using this a lot, so it would be nice to have it in VSpaceCode as well.

see spacemacs [doc](https://develop.spacemacs.org/doc/DOCUMENTATION.html)
> Text related commands (start with x):
> `SPC x o` | use avy to select a link in the frame and open it

## Solution

```json
"key": "x",
"name": "+Text"
"bindings": [
...
	{
		"key": "o",
		"name": "Open link",
		"icon": "link-external",
		"type": "command",
		"command": "editor.action.openLink"
	},
```

## Alternatives
user's settings:

```json
    "vspacecode.bindingOverrides": [
        {
            "keys" : "x.o",
            "name" : "Open link",
            "icon" : "link-external",
            "type" : "command",
            "command" : "editor.action.openLink"
        },
```

**Comment by stevenguh** [comment]
Feature parity is always welcome. Would you like to submit a PR for it?

**Comment by o8vm** [comment]
I've submitted.

**Comment by stevenguh** [comment]
Thanks for submitting the PR. Merged :)
