### ISSUE TITLE
SPC bindigs for tasks

### ISSUE THREAD

**Issue by o8vm** [VSpaceCode/VSpaceCode#236]
## Problem
There are SPC-keybindings for Test and Compile, but it would be nice if there were also keybindings for `workbench.action.tasks.*`.
I also know that test and compile are tied to project in a manner of spacemacs, but I think it would be very useful to be able to systematically execute the following actions with SPC-keybindings. `Tasks ` is a feature of vscode, so can't we create a dedicated key binding for it?

- `workbench.action.tasks.build`
- `workbench.action.tasks.configureTaskRunner`
- `workbench.action.tasks.reRunTask`
- `workbench.action.tasks.restartTask`
- `workbench.action.tasks.test`
- `workbench.action.tasks.runTask`
- `workbench.action.tasks.showLog`
- `workbench.action.tasks.terminate`

## Solution
I'm not sure which bindings are appropriate, but I try creating custom key bindings with SPC k because I thought it was similar to the `kill` command to control the task.

```json
{
            "key": "k",
            "name": "+Tasks",
            "icon": "tasklist",
            "type": "bindings",
            "bindings": [
                {
                    "key": "c",
                    "name": "Run build tasks",
                    "icon": "server-process",
                    "type": "command",
                    "command": "workbench.action.tasks.build",
                },
                {
                    "key": "a",
                    "name": "Configure task runner",
                    "icon": "gear",
                    "type": "command",
                    "command": "workbench.action.tasks.configureTaskRunner",
                },
                {
                    "key": ".",
                    "name": "Rerun last task",
                    "icon": "debug-rerun",
                    "type": "command",
                    "command": "workbench.action.tasks.reRunTask"
                },
                {
                    "key": "X",
                    "name": "Restart running task",
                    "icon": "debug-restart",
                    "type": "command",
                    "command": "workbench.action.tasks.restartTask"
                },
                {
                    "key": "x",
                    "name": "Run task",
                    "icon": "vm-running",
                    "type": "command",
                    "command": "workbench.action.tasks.runTask"
                },
                {
                    "key": "t",
                    "name": "Run test task",
                    "icon": "beaker",
                    "type": "command",
                    "command": "workbench.action.tasks.test"
                },
                {
                    "key": "v",
                    "name": "Show task log",
                    "icon": "comment-discussion",
                    "type": "command",
                    "command": "workbench.action.tasks.showLog"
                },
                {
                    "key": "k",
                    "name": "Terminate task",
                    "icon": "remove",
                    "type": "command",
                    "command": "workbench.action.tasks.terminate"
                },
                {
                    "key": "g",
                    "name": "Show runnung tasks",
                    "icon": "checklist",
                    "type": "command",
                    "command": "workbench.action.tasks.showTasks"
                }
            ]
        }
```

**Comment by stevenguh** [comment]
Task seems like a very integral part of vscode, like debug. I am open to add it to the top menu. @MarcoIeni What do you think?

**Comment by o8vm** [comment]
Since vscode's `Tasks` is feature-rich and highly customizable, if tasks-related commands are enriched, they can be standardized in `Tasks` without having to implement each language-specific major-mode action command separately. 
For example, most of the commands starting with `SPC m c` in the [Rust layer](https://develop.spacemacs.org/layers/+lang/rust/README.html) can be realized with Tasks and rust-analyzer extension in vscode.

**Comment by MarcoIeni** [comment]
> I am open to add it to the top menu

Me too!
`spc k` doesn't seem that easy to remember, though, but I can't find of better replacements.
I thought about `spc a` (application/action) or `spc R` (for run), but I don't like those more than `spc k`.

What about `spc :`? It reminds me of command mode in vim. But `spc k` is more easy to type.

**Comment by o8vm** [comment]
I agree with `SPC :` ! I think it is very good and easy to remember. Typing is not difficult either.

**Comment by o8vm** [comment]
Updated keybind and name to make it easier to remember.

```json
	"name": "+Tasks",
	"icon": "tasklist",
	"type": "bindings",
	"bindings": [
		{
			"key": ".",
			"name": "Rerun last task",
			"icon": "debug-rerun",
			"type": "command",
			"command": "workbench.action.tasks.reRunTask"
		},
		{
			"key": "b",
			"name": "Run build tasks",
			"icon": "server-process",
			"type": "command",
			"command": "workbench.action.tasks.build"
		},
		{
			"key": "c",
			"name": "Configure task runner",
			"icon": "gear",
			"type": "command",
			"command": "workbench.action.tasks.configureTaskRunner"
		},
		{
			"key": "g",
			"name": "Show running tasks",
			"icon": "checklist",
			"type": "command",
			"command": "workbench.action.tasks.showTasks"
		},
		{
			"key": "k",
			"name": "Kill task",
			"icon": "trash",
			"type": "command",
			"command": "workbench.action.tasks.terminate"
		},
		{
			"key": "l",
			"name": "Show task log",
			"icon": "history",
			"type": "command",
			"command": "workbench.action.tasks.showLog"
		},
		{
			"key": "t",
			"name": "Run test task",
			"icon": "beaker",
			"type": "command",
			"command": "workbench.action.tasks.test"
		},
		{
			"key": "x",
			"name": "Run task",
			"icon": "vm-running",
			"type": "command",
			"command": "workbench.action.tasks.runTask"
		},
		{
			"key": "X",
			"name": "Restart running task",
			"icon": "debug-restart",
			"type": "command",
			"command": "workbench.action.tasks.restartTask"
		}
	]
},
```

**Comment by MarcoIeni** [comment]
Yeah, this looks good to me. I would approve the pr. But let's wait for Steven

**Comment by o8vm** [comment]
Yes, by the way 'R' seems to be a better key to assign to "Restart running task" than 'X', right?

**Comment by stevenguh** [comment]
Although `:` has like a command meaning to me, I think it's better than `k` and let's try `:` :). 

> Yes, by the way 'R' seems to be a better key to assign to "Restart running task" than 'X', right?

I agree, `R` is also used as restart debugging in our debug menu `g d`

**Comment by stevenguh** [comment]
Thanks for contributing :) Merged and closed this issue. Will do a release after #239.
