### ISSUE TITLE
Unable to checkout a single commit using Magit

### ISSUE THREAD

**Issue by stagmoose** [VSpaceCode/VSpaceCode#254]
Steps to reproduce:
- `SPC g s`
- `l l`
- move to the commit to be selected (past commits)
- press`ENTER`
- `bb` => only showing branches and press `ENTER` again cannot switch to the commit

Is that normal or did I miss any steps?
Thanks for the effort and magit is so amazing!

**Comment by stevenguh** [comment]
This sounds like a edamagit issue, please open an issue to https://github.com/kahole/edamagit.
