### ISSUE TITLE
Customize yank behavior for some keybinds.

### ISSUE THREAD

**Issue by mpauper** [VSpaceCode/VSpaceCode#255]
## Problem

I would like for vim keybind `c w` to change a word to not copy/yank the work.

## Solution

Maybe there is already a setting I can modify to achieve this, but I am not aware of it.

**Comment by The-Compiler** [comment]
This seems unrelated to VSpaceCode. Vim bindings are coming from the Vim extension, not this one.

**Comment by stevenguh** [comment]
Thanks @The-Compiler. This is indeed a vim issue. Closing this.

`c w` yanking into a register is a vim behavior. You can try using vim remapper (https://github.com/VSCodeVim/Vim#key-remapping) to remap `d` so the delete word into a black hole register.

For example:

```
        {
            "before": ["d"],
            "after": ["\"", "_", "d"]
        }
```

**Comment by mpauper** [comment]
Thanks for the pointers!
