### ISSUE TITLE
Regression with File Explorer toggle (`SPC f t`)?

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#256]
## Bug description

In #79  the "proper" implementation for `SPC f t` was implemented, but it doesn't seem to close the file explorer anymore. Is this a regression? I checked my configs and I'm not overwriting the default behavior so I'm not sure what would be causing this.

## To Reproduce

1. Use `SPC f t` to bring up the file explorer
2. Use `SPC f t` to try and toggle the file explorer closed

## Expected behavior

The file explorer opens and closes (if focused), or the file explorer is focused when it doesn't have focus, as implemented in #79.

## Additional Context

My keymap is pretty massive, but I can repro this with a minimal config on the latest Insiders. Let me know if you need me to share. my config if you can't repro.

## System information

CPUs | Apple M1 Max (10 x 24)
-- | --
GPU Status | 2d_canvas: enabled gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled skia_renderer: disabled_off_ok video_decode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 4, 4
Memory (System) | 64.00GB (3.58GB free)
Process Argv | --crash-reporter-id b3b75191-25ee-4191-9e23-57290ee4b8e3 --crash-reporter-id b3b75191-25ee-4191-9e23-57290ee4b8e3
Screen Reader | no
VM | 0%

**Comment by stevenguh** [comment]
Thanks for opening an issue. It is a regression from a large refactoring in which-key which released in `v0.10.0`. Released which-key `v0.11.1` with the fix.
