### ISSUE TITLE
Add support for `ctrl+]` to cancel actions

### ISSUE THREAD

**Issue by taranlu-houzz** [VSpaceCode/VSpaceCode#264]
## Problem

By default, `vim ` has `ctrl+]` bound to do the same thing as the escape key. I use this binding instead of `esc` since it feels more ergonomic to me.

## Solution

If possible, I would like to just have `ctrl+]` added as an alternative that "does" what `esc` does.

## Additional context

I realize this might be a bit more complicated that it appears. Ideally, this would work for the command palette as well as the VSpaceCode popup (I think that is "which key"? I'm new to VSCode in general...). I looked for a keybinding that would at least work for the command palette, but was unable to find one. It appears that it uses `workbench.action.showCommands` to show the palette, but I don't see any way to change/add an alternative for closing the palette, so I don't know if this can actually be solved. It would be nice if it could at least work for the VSpaceCode part though.

**Comment by stevenguh** [comment]
For vscode vim, you can rebind key using their key bindings. See https://github.com/VSCodeVim/Vim. 

For example, you can add the following to your `settings.json`.
```json
"vim.insertModeKeyBindings": [
	{
		"before": ["<C-]>"],
		"after": ["<Esc>"]
	}
]
```

For the "VSpaceCode popup", you can add the following to your `keybindings.json`.
```json
{
	"key": "ctrl+]",
	"command": "workbench.action.closeQuickOpen",
	"when": "whichkeyVisible"
}
```
Change value of `"when"` to `inQuickOpen` if you can `C-]` to be applicable to all the quick open menu in vscode.

**Comment by taranlu-houzz** [comment]
Never mind. The keybinding works (I was expecting `ctrl+[`, not `ctrl+]`).
