### ISSUE TITLE
Support evil-easymotion bindings (SPC j l) for deletions and yanking

### ISSUE THREAD

**Issue by baygeldin** [VSpaceCode/VSpaceCode#265]
First of all, thank you for this amazing project! 🙏 It really eased my transition from Spacemacs to VScode.

## Problem

In Spacemacs there is the `evil-easymotion` package that is used to navigate the code easily with `SPC j w` (jump to word) and `SPC j l` (jump to line) bindings. VSpaceCode supports it too (and it's great!), but the one thing I'm missing is to be able to use it with deletions and yanking. For example, in Spacemacs when I wanted to delete/cut a bunch of lines from the line the cursor is currently on to the line I specified with `SPC j l` I could just do `d SPC j l`. In VSpaceCode I need to do it manually (the full sequence is `0 v SPC j l <line identifier> $ d`). The same issue goes for yanking (i.e. `y SPC j l`).

## Solution

I'm not really sure how to implement it. Might there be some issues because deletion and yanking are not modes? 

## Alternatives

Currently I use `d <line number> G` and `y <line number> G` to achieve the same thing, but it's a but clunky.

**Comment by stevenguh** [comment]
For commands like `SPC j l`, we are just issuing keys (in this example `<leader><leader><leader> bdjk`) to vscode. It's very unfortunate that VsCode Vim doesn't support having EasyMotion with action at the moment. See https://github.com/VSCodeVim/Vim/issues/4624.

**Comment by stevenguh** [comment]
I will close this as there isn't much we can do. One side path I can imagine is use neovim integration; however, it is not the path that I've much experience in nor there's much support in this repo atm.
