### ISSUE TITLE
Cannot remove binding for period, "."

### ISSUE THREAD

**Issue by Ultramann** [VSpaceCode/VSpaceCode#270]
## Bug description
I'd like to remove the binding for `.`.

Following the [documentation for removing](https://vspacecode.github.io/docs/menu-customization#removal) bindings I tried adding the following to my `settings.json` file.

``` jsonc
{
  "vspacecode.bindingOverrides": [
    {
      "keys": ".",
      "position": -1,
    }
}
```
But the setting doesn't seem to have any effect.

## To Reproduce
Add the following to your `settings.json` file.

``` jsonc
{
  "vspacecode.bindingOverrides": [
    {
      "keys": ".",
      "position": -1,
    }
}
```
Check if the `.` key is still listed.

## Expected behavior
The `.` option should not be shown in the which key menu.

## Screenshots

<img width="370" alt="image" src="https://user-images.githubusercontent.com/9347171/161454618-48f9acfe-cf78-4192-914d-7bd77cb1dfe0.png">

**Comment by stevenguh** [comment]
You should able to use `"keys": ["."]`. As `.` is used as the separator in `keys` so different syntax is needed for this case.

**Comment by Ultramann** [comment]
Works like a charm, many thanks.
