### ISSUE TITLE
Cannot use bindingOverrides for "*" 'Search in project with selected'

### ISSUE THREAD

**Issue by psnelgrove-r7** [VSpaceCode/VSpaceCode#274]
## Bug description

I've been using the SearchEditor feature over the main search panel and I have the default search set to open a new search editor. `/` works as expected but `*` will open the search panel because it invokes `search.action.focusSearchList`. When I go to override the command like below, the override never picks up. I did verify that overrides as [documented](https://vspacecode.github.io/docs/menu-customization/) in the project website and those all work as expected.

## To Reproduce
Add the following override and it won't pick up.

```json
"vspacecode.bindingOverrides": [
    {
        "key": "*",
        "name": "Search in project with this awesome override!",
        "icon": "search",
        "type": "commands",
        "commands": [
            "editor.action.addSelectionToNextFindMatch",
            "workbench.action.findInFiles",
            // "search.action.focusSearchList"
        ]
    },
],
```

## Expected behavior

You can override the non-nested commands.

## Additional context

I found this other ticket #270 that hints that the `.` splitting of the key path is the issue. I did try to wrap the key in a list like `"key": ["*"],` but it didn't work. I think #270 that's only an issue because it's using the actual delimiter.

**Comment by stevenguh** [comment]
I think you need to use `keys` instead of `key`
