### ISSUE TITLE
Insert mode doesn't work after searching for text

### ISSUE THREAD

**Issue by nicwhitts** [VSpaceCode/VSpaceCode#281]
## Bug description

I find a really annoying bug, after searching for text within the file (CMD + F). When exiting the search, the insert mode is really buggy.

## To Reproduce

In a file, hit CMD + F. 
Type some text for a match
Hit CMD + G to go to next occurrence
Hit escape to exit search

Insert mode won't work. Usually have to hit ESCAPE at least one more time

## Expected behavior

Expect to be able to exit search and then enter INSERT mode right away.
Really slows down productivity. 
## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
// Copy paste the content of your keybindings.json file here.
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
// Copy paste the content of your settings.json file here.
```

</p>
</details>

**Comment by stevenguh** [comment]
This will be an issue under https://github.com/VSCodeVim/Vim. Free feel to see if there's an issue there already.
