### ISSUE TITLE
Add folder to workspace

### ISSUE THREAD

**Issue by nicwhitts** [VSpaceCode/VSpaceCode#284]
## Problem

I think it would be cool to mimic emacs behaviour of projects by having the ability to add a folder to the current workspace.

Not the current action (add folder to workspace) - where you choose the folder to add with the open dialog.
## Solution

An option like SPC - p which shows recent opened folders. Instead of opening the folder in the current or new window. It adds to the workspace.

**Comment by stevenguh** [comment]
Do you have an example maybe a screen capture of which emacs behavior?
