### ISSUE TITLE
top of menu still showing, even with whichkey delay set

### ISSUE THREAD

**Issue by patrickaldis** [VSpaceCode/VSpaceCode#286]
With the whichkey delay enabled as described in [here](https://vspacecode.github.io/docs/whichkey/extra) I still get the whichkey popup appearing immediately, just with no entries. It just takes _delay_ amount of time to load the entries

Example:
![image](https://user-images.githubusercontent.com/46719614/200983808-cec81f49-93fa-4003-85bf-18a86fe03bdc.png)

**Comment by stevenguh** [comment]
This is work as intended. We cannot take any input with that popup; hence, delay only delays showing of the entries.
