### ISSUE TITLE
File browser extension doesn't work with VS Code 1.73.1 on Mac M1

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#287]
## Bug description

[File Browser](https://marketplace.visualstudio.com/items?itemName=bodil.file-browser) extension doesn't let you browse the files.

## To Reproduce

1. Press `spc f f`.
2. Then go "left" or "right".
3. Now you can't go "up" or "down".

## Expected behavior

You should be able to 

## Screenshots

![image](https://user-images.githubusercontent.com/11428655/201468483-fa9d45a8-997e-4ce3-96bf-661488f309cc.png)
From here, "up" and "down" does nothing.

## System information

![image](https://user-images.githubusercontent.com/11428655/201468571-e2094998-a6e0-4ade-80fa-94839a42162d.png)

## Solution

This extension is unmaintained. Here are some forks:
- https://github.com/atariq11700/vscode-file-browser (In the [CHANGELOG](https://github.com/atariq11700/vscode-file-browser/blob/master/CHANGELOG.md#0214) it mentions they fixed it). However, it doesn't work in my M1.
- https://github.com/jeffgran/vscode-quick-file-browser
- https://github.com/ctf0/vscode-quick-file-browser
- https://github.com/kaigedong/vscode-file-browser

There is also an unmerged [PR](https://github.com/bodil/vscode-file-browser/pull/27) opened by Steven.

I suggest we bring this extension inside our repository, so that users don't have to install another extension when they install VSpaceCode.
An alternative is that we use one of the forks as an extension.

**Comment by MarcoIeni** [comment]
Actually, I've seen there's some activity from the maintainer [here](https://github.com/bodil/vscode-file-browser/issues/35).

**Comment by stevenguh** [comment]
That's a a very interesting bug and confirmed it doesn't work on my m1 Mac as well. I suspect this is quick pick API regression of [vscode v1.73 with the style updates](
https://code.visualstudio.com/updates/v1_73#_quick-pick-list-style-updates). Have you look to see if there's any bug opened in vscode about this?

> This extension is unmaintained. Here are some forks:

I don't mind switching to a different forks or bring into the VSpaceCode "org" and republish it. However, my capacity is limited...it might be better to switch to a different forks?

> I suggest we bring this extension inside our repository, so that users don't have to install another extension when they install VSpaceCode.

Unfortunately, the file-browser license is not compatible with MIT (this repo's license). Can't directly embed into this repo but still can fork it and republish the extension.

**Comment by MarcoIeni** [comment]
> the file-browser license is not compatible with MIT (this repo's license). Can't directly embed into this repo

That's unfortunate.

Since we have limited capacity and the maintainer said they will look into it, I suggest sticking with the original extension and waiting for it to be fixed. 👍 

Now that I think about it, extensions are a security threat to our users, so switching to random forks might not be the best 😅

**Comment by stevenguh** [comment]
> Now that I think about it, extensions are a security threat to our users, so switching to random forks might not be the best 😅

That's a good point. Especially when there are many random forks. The only way we ensure it is the bring it into the our org.

> Since we have limited capacity and the maintainer said they will look into it, I suggest sticking with the original extension and waiting for it to be fixed. 👍

Let's wait for bit and see if it is a regression of vscode or if there's some async bug in file-browser.

**Comment by max-sixty** [comment]
I think closed by https://github.com/bodil/vscode-file-browser/pull/37 ?

**Comment by stevenguh** [comment]
Seems to have fixed it. Closed.
