### ISSUE TITLE
Elixir major mode

### ISSUE THREAD

**Issue by tomekowal** [VSpaceCode/VSpaceCode#292]
## Problem

I am an Elixir programmer that came from Spacemacs to VSCode. The project works brilliantly, except major mode shortcuts: "SPC m ..." or ", ...".

## Solution

Elixir community settled on [ElixirLS: Elixir support and debugger](https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls). I could add keybindings for it in `package.json` similar to other supported languages and then update the documentation GitHub Pages.

## Alternatives

I am currently adding `vspacecode.bindingOverrides` in my private `settings.json`. It works, but I don't have full coverage of everything that elixir-lsp offers in Spacemacs. Only things that I use most often. It would be nice to have Elixir out of the box :)

## Additional context

I could make a PR, but it looks like Elixir's major mode has many keybindings. I might need help identifying which Spacemacs function matches which Visual Studio Code function and if there is a one-to-one match.

If you like the idea, let me know if I should open a draft PR with what I have or if you'd rather wait until it is fully done.

**Comment by MarcoIeni** [comment]
Hi! We are happy to accept new major modes. You can find the main issue [here](https://github.com/VSpaceCode/VSpaceCode/issues/98).

> It works, but I don't have full coverage of everything that elixir-lsp offers in Spacemacs. Only things that I use most often

It's fine, you can open a small pr at the beginning, and then you or other elixir developers can add more key bindings later. The PR doesn't need to cover 100%. It's also easier to work/review smaller PRs 👍 

> I might need help identifying which Spacemacs function matches which Visual Studio Code function and if there is a one-to-one match.

Try to look at [other](https://github.com/VSpaceCode/VSpaceCode/blob/fafc4e46ea3c72b780ebd73d7254f0cade5cfdcd/package.json#L1561) major modes first.
If you still have questions we can discuss in the PR 👍

**Comment by tomekowal** [comment]
Eh, sorry. I jumped too quickly, and I can't continue working on this.
I am closing the issue to not clutter too much and because you've pointed out there is already a central issue for major modes.
