### ISSUE TITLE
Make VSpaceCode a verified publisher

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#296]
## Problem

It would be nice to have a verified blue check in VSCode.

## Solution

We need to follow [these](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher) instructions.

This can be done just by the maintainers of the extension.
I am one of the maintainers of this extension together with Steven.
However, I tried logging in the [marketplace](https://marketplace.visualstudio.com/vscode), but my account seems to not be linked with the VSpaceCode extension anymore, I don't know why. (Steven if you have time can you write me an email to check if it's all good on your side?).
So at the moment, only Steven can do it.

**Comment by stevenguh** [comment]
We will need a domain it seems. Would say nice to have, but vscode vim also doesn't have the blue check mark..haha

> However, I tried logging in the [marketplace](https://marketplace.visualstudio.com/vscode), but my account seems to not be linked with the VSpaceCode extension anymore, I don't know why. (Steven if you have time can you write me an email to check if it's all good on your side?).
> So at the moment, only Steven can do it.

Weird, I haven't changed anything. Will double check and PM.

**Comment by MarcoIeni** [comment]
> We will need a domain it seems.

Can't we use https://vspacecode.github.io/ ? 🤔

**Comment by stevenguh** [comment]
Unfortunately one of the requirements is:

> Cannot be a subdomain ({subdomain}.github.io, {subdomain}.contoso.com, or similar).

**Comment by MarcoIeni** [comment]
I see, I'll close this issue than.
I'll debug my access to the marketplace when I find some time.

**Comment by stevenguh** [comment]
> I see, I'll close this issue than.

Sounds good to me

> I'll debug my access to the marketplace when I find some time.

Feel free to let me know if you need any help
