### ISSUE TITLE
SpaceMacs space does not activate on fresh install

### ISSUE THREAD

**Issue by tech0tron** [VSpaceCode/VSpaceCode#300]
Clicking space does nothing on a fresh VsCode install with no extensions or settings. No which-key popup appears, and trying things like saving a file (<spc> f s) does nothing.

**Comment by MarcoIeni** [comment]
As a temporary workaround, you can follow [this](https://vspacecode.github.io/docs/#manual-configuration-optional) guide.

**Comment by stevenguh** [comment]
Yes you will need to install the VSpaceCode extension and have the right configuration. Closing this for now. Let us know if you still encounter any issue after installing the extension.
