### ISSUE TITLE
Space + F + F opens up file navigation, but using arrows make editor lose focus on the prompt

### ISSUE THREAD

**Issue by CMCDragonkai** [VSpaceCode/VSpaceCode#305]
## Bug description

I'm not sure if this is due to recent vscode changes or vspacecode. But now if you do Space + F + F, it loses focus when you go left or right on the arrow keys.

This makes it inconvenient when navigating around the filesystem unlike before.

## To Reproduce

I'm using 1.73.1 of VsCode with 0.10.14 of VSpaceCode.

## Expected behavior

It should work like in the past, the focus on the prompt should stay on, so I can type letters while going left and right.

## System information

<details>

```
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.10.167
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz (8 x 3856)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.39GB (5.38GB free)|
|Process Argv|--extensions-dir /nix/store/m3pq29bjn02653k0si5lwcspz25g8a76-vscode-extensions/share/vscode/extensions --crash-reporter-id 3c06c835-b333-413c-8eb9-3e8f0113d174|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/nix/store/7422jp7q4122jhh97b0jakmj4gw90x76-desktops/share/xsessions/none+xmonad|
|XDG_CURRENT_DESKTOP|xmonad|
|XDG_SESSION_DESKTOP|xmonad|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   142	 72671	code main
    0	    32	 72674	   zygote
    1	    95	 72705	     gpu-process
    0	    32	 72675	   zygote
    0	     0	 72677	     zygote
    0	    63	 76250	       issue-reporter
    0	    47	 72720	   utility-network-service
    0	   268	 72746	   window (config.nix - polykey (Workspace) - Visual Studio Code)
    0	   173	 72768	   extensionHost
    0	    63	 72985	     /nix/store/fyzd4v1ji8493kxr3n68yhbwwp182jya-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node /nix/store/fyzd4v1ji8493kxr3n68yhbwwp182jya-vscode-1.73.1/lib/vscode/resources/app/extensions/markdown-language-features/server/dist/node/main --node-ipc --clientProcessId=72768
    0	   725	 73076	     /nix/store/axfr6gf5078hrr6dd18xn8jvk35sdrfv-rust-analyzer-unwrapped-2022-10-31/bin/rust-analyzer
    0	     0	 73234	       /nix/store/w5xd5z4x0dka65n530hsrami8qxcc0b3-rustc-1.64.0/libexec/rust-analyzer-proc-macro-srv
    0	     0	 73235	       /nix/store/w5xd5z4x0dka65n530hsrami8qxcc0b3-rustc-1.64.0/libexec/rust-analyzer-proc-macro-srv
    0	   110	 74581	     /nix/store/fyzd4v1ji8493kxr3n68yhbwwp182jya-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /home/cmcdragonkai/Projects/js-errors/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /tmp/vscode-typescript1000/cf7ca8e86205305ac8f6/tscancellation-8a4e075b0ce7539e9f4f.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   252	 74582	     /nix/store/fyzd4v1ji8493kxr3n68yhbwwp182jya-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node --max-old-space-size=3072 /home/cmcdragonkai/Projects/js-errors/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/cf7ca8e86205305ac8f6/tscancellation-51cf7756cd566e57fc3b.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    79	 74602	       /nix/store/fyzd4v1ji8493kxr3n68yhbwwp182jya-vscode-1.73.1/lib/vscode/code --ms-enable-electron-run-as-node /home/cmcdragonkai/Projects/js-errors/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /home/cmcdragonkai/.cache/typescript/4.9 --enableTelemetry --typesMapLocation /home/cmcdragonkai/Projects/js-errors/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	   110	 72782	   shared-process
    0	    63	 72802	     ptyHost
    0	   110	 72828	     fileWatcher
    0	     0	 76267	     /run/current-system/sw/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (config.nix - polykey (Workspace) - Visual Studio Code)
|    Folder (js-async-cancellable): 98 files
|      File types: map(11) ts(9) png(4) html(4) json(4) css(3) js(3) yml(2)
|                  nix(2) editorconfig(1)
|      Conf files: github-actions(1) package.json(1) tsconfig.json(1)
|    Folder (js-db): 178 files
|      File types: html(35) ts(29) h(25) cpp(14) json(7) png(4) js(4) txt(3)
|                  gyp(3) css(3)
|      Conf files: github-actions(1) package.json(1) tsconfig.json(1)
|    Folder (Polykey-Docs): 156 files
|      File types: md(81) png(11) puml(4) json(4) js(3) svg(2) nix(2)
|                  editorconfig(1) example(1) gitignore(1)
|      Conf files: tsconfig.json(2) package.json(1)
|    Folder (js-errors): 145 files
|      File types: map(25) ts(12) js(6) html(5) json(4) yml(2) css(2) nix(2)
|                  editorconfig(1) example(1)
|      Conf files: github-actions(1) package.json(1) tsconfig.json(1)
|    Folder (Polykey): 3025 files
|      File types: ts(1015) html(776) js(456) map(407) proto(44) json(22)
|                  txt(13) sh(6) nix(5) png(4)
|      Conf files: github-actions(1) package.json(1) tsconfig.json(1)
|    Folder (js-quic): 2537 files
|      File types: o(634) d(405) json(173) timestamp(169) rmeta(98) rlib(52)
|                  bin(42) ts(35) cmake(15) make(15)
|      Conf files: cmake(15) package.json(1) makefile(1) tsconfig.json(1)
|    Folder (quiche): 4651 files
|      File types: timestamp(198) json(197) d(153) o(115) rmeta(113) rs(65)
|                  rlib(24) bin(24) ll(16) lock(9)
|      Conf files: github-actions(3) dockerfile(2) makefile(2);
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
copilot|Git|1.73.8685
vspacecode|VSp|0.10.14
whichkey|VSp|0.11.3
file-browser|bod|0.2.10
gitlens|eam|12.1.2
go|gol|0.33.1
haskell|has|2.2.0
fuzzy-search|jac|0.0.3
nix-ide|jno|0.2.1
svg|joc|1.4.19
magit|kah|0.6.36
python|ms-|2022.17.13011006
cpptools|ms-|1.11.0
vscode-typescript-next|ms-|4.7.20220327
vetur|oct|0.34.1
vscode-yaml|red|1.9.1
rust-analyzer|rus|0.3.1059
even-better-toml|tam|0.14.2
vim|vsc|1.24.1
vscode-proto3|zxh|0.5.4


</details>
<!-- generated by issue reporter -->
```

</details>

**Comment by MarcoIeni** [comment]
You are using the extension `file-browser|bod|0.2.10`
The latest one is 0.2.11. Can you update it?
![image](https://user-images.githubusercontent.com/11428655/219313309-31fb8ba3-0773-44b5-958e-9113ec65c8ed.png)

**Comment by CMCDragonkai** [comment]
That worked, thanks!
