### ISSUE TITLE
Close active window using ␣ w q (as alternative to ␣ w d)

### ISSUE THREAD

**Issue by hyperfocus1337** [VSpaceCode/VSpaceCode#306]
## Problem

I'm using to closing the active window using `␣ w q` (instead of `␣ w d`) in Doom Emacs. However, when I try to configure it using the below code snippet in `settings.json`, it doesn't seem to be working. The option doesn't appear in the menu.

```
{
    "vspacecode.bindingOverrides": [
        {
            "key": "w.q",
            "name": "Close active window",
            "icon": "close",
            "type": "command",
            "command": "workbench.action.closeEditorsInGroup"
        }
    ]
}
```

## Solution

Make it work like it normally should.

**Comment by MarcoIeni** [comment]
You are missing an `s`. Try with `"keys": "w.q",`
