### ISSUE TITLE
Overrides file to closely mimick default Doom Emacs keybindings?

### ISSUE THREAD

**Issue by hyperfocus1337** [VSpaceCode/VSpaceCode#307]
## Problem

I understand this project is inspired from Spacemacs, thus containing Spacemacs keybindings. However, personally I use Doom Emacs as my main driver, and the keybindings differ slightly between these two projects.

I can't help but wonder if there are any other Doom Emacs users which have customized the preprogrammed keybindings in this project to closely align with the keybindings in Doom Emacs.

If there are, I would appreciate it if someone could share their `vspacecode.bindingOverrides` configuration.

## Solution

Share me your `vspacecode.bindingOverrides` configuration that closely mimicks Doom Emacs keybindings!

## Alternatives

I am in the process of assembling my own overrides, once they're in a more developed stage I could share them here. However it'll likely only contain the keybindings I use frequently in Doom Emacs (and which differ from the Spacemacs bindings).

Not sure if I intend it to be feature complete, although it would be a nice exercise to learn new keybindings.

(and awesome project btw, thanks for developing it!)

**Comment by MarcoIeni** [comment]
Great initiative!
You can submit a doom-emacs-like configuration [here](https://github.com/VSpaceCode/community-configs)

**Comment by hyperfocus1337** [comment]
I have!

It's here: https://github.com/VSpaceCode/community-configs/pull/4

Once again thanks for building this extension!
