### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by brianedelman** [VSpaceCode/VSpaceCode#31]
Currently can't find this in the vscode marketplace so wondering how I can use this.

**Comment by StreakyCobra** [comment]
Depend what you mean by still active. The project is currently not an extension, so you won't find it on the marketplace. Instead, it is some configurations that you can manually put inside your VSCode configuration (it's explained [here](https://github.com/VSpaceCode/VSpaceCode#installation)) to have it behave partially like Spacemacs.

If you or anyone have knowledge and time to contribute, by sending configuration for missing bindings or to make an extension out of it, contributions are welcome. I am also open to give write access to people interested to contribute seriously or even to take over :)

**Comment by crucialfelix** [comment]
It's not clear from the README.md at all that this is not a package to be installed. There is a section for installation which implies that it is something that can be installed. 

From the installation docs it is odd that it goes from "install VSCodeVim" (which is called just Vim in the marketplace) to the section about changing the settings.json file. 

But it still didn't occur to me that this isn't a VSCode package at all (I was searching in the marketplace for it). I only figured it out when I read this issue.

It would help if you added something that clearly explains that this is just settings.json and keybindings.json file that need to be manually merged.

Thanks

**Comment by StreakyCobra** [comment]
Thanks for the feedback. When you are making a project there are information that are obvious to you but not to newcomers :) 

I've several PR / issues to address, I'll add your concern to my list. I'm still trying to find some time for doing them though.

**Comment by crucialfelix** [comment]
Yep, I totally understand that! It's hard to read what you've written with a blank slate mind. I know it's also hard to find the time. Thanks!
