### ISSUE TITLE
How to define key sequence with the effect of `evil-escape-key-sequence`?

### ISSUE THREAD

**Issue by concretevitamin** [VSpaceCode/VSpaceCode#310]
Hello,

This is a great extension, thanks for making it. 

A quick question as I adjust to it. In my `.spacemacs` I have
```
  (setq-default evil-escape-key-sequence (kbd "jj"))
```
Namely typing `jj` while editing something would escape me back to normal mode. Is there a simple way to define this in VSpaceCode? Searching "escape" in `settings.json` and in docs returns no results.

**Comment by MarcoIeni** [comment]
Hey 👋 

From https://github.com/VSCodeVim/Vim readme:

```
"vim.insertModeKeyBindings": [
    {
      "before": ["j", "j"],
      "after": ["<Esc>"]
    }
  ],
```

**Comment by concretevitamin** [comment]
Thanks! Works for me!

**Comment by LeaveNhA** [comment]
This might be considered as default behavior and binding.

**Comment by stevenguh** [comment]
I don't think this is the default with spacemacs, so we probably won't consider it to be default.
