### ISSUE TITLE
Using `/` to search: results are not highlighted as does `CMD+f`?

### ISSUE THREAD

**Issue by concretevitamin** [VSpaceCode/VSpaceCode#315]
## Problem

I used `/` to search for a word but the  results are not highlighted the same way `CMD+f` would highlight the results. 

Any settings to change this behavior?

**Comment by stevenguh** [comment]
This is mostly about how vscode vim implements this. There are some customization you can do, see https://github.com/VSCodeVim/Vim.

For example: Setting `vim.hlsearch` to true allow vscode vim to search and highlight as you type.

Closing this as it is not related to this extension. Let me know if you still have any issue.
