### ISSUE TITLE
Maximizing windows (`SPC w m`) does not truly maximize windows?

### ISSUE THREAD

**Issue by concretevitamin** [VSpaceCode/VSpaceCode#316]
## Bug description

Maximizing windows (`SPC w m`) does not truly maximize windows. It leaves other windows/splits partially visible.

Any way to customize / fix this?

## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
// Copy paste the content of your keybindings.json file here.
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
// Copy paste the content of your settings.json file here.
```

</p>
</details>

**Comment by stevenguh** [comment]
I couldn't find a vscode command to actually maximum the window. Let me know if you find a command the actually maximum the window. We can update it.

**Comment by LonelySteve** [comment]
In the latest version of vscode (v1.84), the "View: Toggle Maximize Editor Group" command has been added, which can be used to maximize the editor group.

**Comment by MarcoIeni** [comment]
just tried it and seems nice! LonelySteve, do you want to raise a pr? :)

**Comment by LonelySteve** [comment]
> just tried it and seems nice! LonelySteve, do you want to raise a pr? :)

No, I don't know how to make sure the previous vscode versions work

But actually, just change the settings file:

```json
{
    "keys": "w.m",
    "name": "maximize editor group",
    "type": "command",
    "command": "workbench.action.toggleMaximizeEditorGroup"
}
```

**Comment by MarcoIeni** [comment]
> No, I don't know how to make sure the previous vscode versions work

You can look at this pr for inspiration. You just need to change this line:
https://github.com/VSpaceCode/VSpaceCode/blob/0a7d9ad32a2cea0bca008c539e1df6482ea52765/package.json#L8448

I also propose to move `toggleEditorWidths` to `spc w M`. What do you think?

**Comment by LonelySteve** [comment]
I've found that `spc w M` gives an error in the latest version of vscode.

It seems that the command ID has been changed from "workbench.action.maximizeEditor" to "workbench.action.maximizeEditorHideSidebar".

> I also propose to move toggleEditorWidths to spc w M. What do you think?

I can create a PR as you suggested, but are you sure we don’t need to consider previous versions of vscode?

**Comment by MarcoIeni** [comment]
> I can create a PR as you suggested, but are you sure we don’t need to consider previous versions of vscode?

Oh, I see what you mean now, sorry 😅 

> are you sure we don’t need to consider previous versions of vscode?

I'm fine with VSpaceCode only supporting the latest stable release. Otherwise, the maintenance burden becomes too much. People on old vspace code versions can use old vspacecode versions.

Curious to see what Steven thinks 👍

**Comment by stevenguh** [comment]
> People on old vspace code versions can use old vspacecode versions.

Sounds reasonable to me and a user can always
1. Use the old version
1. Or override the bindings to the old binding if they wish.

---

Free feel to create a PR. That would be great especially this aligns pretty well with spacemacs.
