### ISSUE TITLE
`SPC b b` (show all buffers) input bar shows some prefilled text `edt mru `

### ISSUE THREAD

**Issue by concretevitamin** [VSpaceCode/VSpaceCode#319]
## Bug description
`SPC b b` (show all buffers) brings up an input bar for user to search through buffers, and the bar shows some prefilled text `edt mru `.

This does not appear to affect search results, albeit surprising to see.

## Expected behavior

Input bar without any characters in it.

## Keybindings

<details><summary>Click to toggle contents of `keybindings.json`</summary>
<p>
  
```jsonc
// Copy paste the content of your keybindings.json file here.
```

</p>
</details>

## Settings

<details><summary>Click to toggle contents of `settings.json`</summary>
<p>

```jsonc
// Copy paste the content of your settings.json file here.
```

</p>
</details>

**Comment by The-Compiler** [comment]
This is just VS Code behavior, nothing to do with this extension.

If you run `SPC SPC` (or Ctrl-Shift-P with vanilla VS Code), and run the "View: Show All Editors By Most Recently Used" command, you'll end up with exactly the same prompt (and, as an aside, even the command palette has the input prefilled with a `>` too).
