### ISSUE TITLE
which-key support

### ISSUE THREAD

**Issue by Froziph** [VSpaceCode/VSpaceCode#32]
Hey there! I am also looking for the Spacemacs experience in VSCode. I saw this plugin: https://marketplace.visualstudio.com/items?itemName=michaelgriscom.leadermode which 'simulates' which-key, so that you don't have to remember every single step. It is however not compatible with the Vim plugin. Think it would be possible to get this which-key feature from Emacs in here using Vim / VSpaceCode :D?

**Comment by StreakyCobra** [comment]
Hi! They say it is not possible to use the two together because:

> LeaderMode should not be used in combination with Vim extensions due to a VSCode limitation.

So I guess we can't do really more here. And for now this project is just a set of configurations, not even an extension, so we are faaar from this :)

**Comment by StreakyCobra** [comment]
There is nothing more I can do on this side, so closing it for now :) Feel free to open another issue if anything new appears regarding "which-key"-like behavior on VSCodeVim
