### ISSUE TITLE
Space not working to show the menu 

### ISSUE THREAD

**Issue by eggcaker** [VSpaceCode/VSpaceCode#321]
## Bug description

After install the VSpaceCode on vscode insider(version: 1.79.0-insider), press the space in normal mode, the base menu not popup, but press Ctrl+Shift+P , type `show VSPace Code Menu ` works.
 
## To Reproduce
Steps to reproduce the behavior. Something like:
1. Install the latest version of insider
2. Install the VSpaceCode from extension mananger
3. Press Space to show menu 
4.  Nothing shows 

## Expected behavior

the menu should be popup like before.
## System information
- Windows11 
- vscode 1.79.0-insider 
- VSpaceCode latest version 
   Published
  6/20/2020, 01:30:00
   Last released
  2/11/2023, 13:47:26  
  Last updated
  5/24/2023, 21:06:12
  Identifier
  vspacecode.vspacecode

**Comment by stevenguh** [comment]
Does it work on non-insider?

Usually there is a walkthrough on first install to guide you how to setup, check out https://vspacecode.github.io/docs/ for the installation

**Comment by eggcaker** [comment]
it's working on stable release of vscode.

**Comment by stevenguh** [comment]
I just tested it seems to worked fine for me.

Try [Ctrl/Cmd]+Shift+P  and executes `VSpaceCode: Configure Default Settings and Keybindings` to reconfigure the settings for the vscode insider.

**Comment by eggcaker** [comment]
reconfigure the settings and bindings fixed. works now!
