### ISSUE TITLE
Stop vspacecode.space from displaying when activated

### ISSUE THREAD

**Issue by phuvp** [VSpaceCode/VSpaceCode#334]
## Problem

When I use vspacecode.space, the command launcher pops up and covers the screen. Given how often I activate vspacecode.space, it is disruptive and blocks visibility of code.
## Solution

It'd be great to have a +UI Toggle to not display the command launcher when activating vspacecode.code and launching commands

**Comment by phuvp** [comment]
<img width="1253" alt="image" src="https://github.com/VSpaceCode/VSpaceCode/assets/6632710/2a129f4b-cb15-4725-aa12-94d1cef73b7b">
The launcher's screen estate for context.

**Comment by stevenguh** [comment]
Setting `whichkey.delay` to non-zero should help this case by delaying the display of the full menu while having the key functional.

<img width="440" alt="image" src="https://github.com/VSpaceCode/VSpaceCode/assets/3455662/ef3e23e4-d1fc-403c-9cb3-93f0a40a1675">

**Comment by phuvp** [comment]
Thank you for the help @stevenguh ,
I've made the edits and the results now look like this. After the change, there is still a bar that appears, even if the launcher menu does not appear. It's much less obtrusive. 
Do you know if I can disable the bar being displayed as well, or at least move the behavior to the bottom of my screen, so it's less in my direct line of sight?
![image](https://github.com/VSpaceCode/VSpaceCode/assets/6632710/e769a6af-77a9-4bad-b398-74b07824a407)

**Comment by stevenguh** [comment]
Unfortunately, that "bar" is how we interrupt input and can't be complete hidden. 

I have seen some success in modifying this quickInpput style from people in the past: https://vspacecode.github.io/docs/whichkey/extra#style-the-menu-with-customize-ui
That could be one direction you can try.

**Comment by stevenguh** [comment]
You can also try use the old approach that uses vscode vim bindings with [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) branch.

Closing this as this is a known limitation with the current approach and vscode API
