### ISSUE TITLE
Clojure refactoring commands are broken

### ISSUE THREAD

**Issue by jbullers** [VSpaceCode/VSpaceCode#345]
## Bug description

Refactoring commands in Clojure mode don't work. For example, trying to add a missing import by typing `, r a l` gives the following error:

```
Error: command 'calva.refactor.addMissingLibspec' not found
```

## To Reproduce

1. Have the Calva extension installed
2. Open a Clojure source file
3. `, r` to enter the refactoring menu
4. Any choice from there is broken

## Expected behavior

From what I can tell, this should be just a find-and-replace. According to the [Calva documentation](https://calva.io/refactoring/), the commands are prefixed with `clojureLsp.refactoring` instead of `calva.refactoring`. Taking the example above, the command should be `clojureLsp.refactor.addMissingLibspec`

**Comment by stevenguh** [comment]
Good catch! Would you mind submitting a PR for this? Since I don't really use Clojure, it would be hard for to test.

**Comment by jbullers** [comment]
Sure, I'll give it a go in the next week or so

**Comment by jbullers** [comment]
I'm a little stumped. I run VS Code with my project in WSL Ubuntu. When I launch the extension via debug, it tells me:
```
Cannot activate the 'VSpaceCode' extension because it depends on the 'Which Key' extension, which is not loaded. Would you like to reload the window to load the extension?
```

Reloading doesn't change anything, yet I see 'Which Key' listed in my extensions.

**Comment by stevenguh** [comment]
Depending how you are running your setup. I think you may need to install `which-key` in the remote. There are two ways extension works

1. Extensions are installed in the the host
3. Extensions are installed in the remote

I assumed you set up VSpaceCode project in your remote; hence, when it is launching, it is running in the remote and require which-key to be install in the remote as well.

**Comment by jbullers** [comment]
Hmm... Usually, plugins show in "local" and give an option to install in WSL. When I run the VSpaceCode extension, it still shows in "local", as does 'Which Key'. I don't see any option to install 'Which Key' in WSL as well. I'll try and figure something out.

**Comment by stevenguh** [comment]
I haven't done that in a while. I remembered running/testing extension in the remote is a little bit tricky.
