### ISSUE TITLE
Inconsistent bindings for refactor rename in Rust major mode

### ISSUE THREAD

**Issue by siboehm** [VSpaceCode/VSpaceCode#349]
I've noticed that different language major modes will handle renaming differently:
- C++ & CUDA & Go: Space -> m -> refactor -> rename
- Rust: Space -> m -> action -> rename

VSpaceCode [conventions](https://vspacecode.github.io/docs/conventions/) list `SPC m a r` as `Execute refactor action`.

Spacemacs LSP layer [docs](https://develop.spacemacs.org/layers/+tools/lsp/README.html) list `SPC m r r` as `rename` 

Just to clarify, SPC m r r is correct binding, right? Then I'll adjust the Rust major mode, update the docs and will also try adding rename for Python. I can also look at the other major modes and try to make them consistent

**Comment by stevenguh** [comment]
I think the inconsistency is mostly trying to match what spacemacs has and I assume spacemacs started with LSP, but the command are really up to each major mode.
