### ISSUE TITLE
Flutter commands are outdated

### ISSUE THREAD

**Issue by PatrickWulfe** [VSpaceCode/VSpaceCode#354]
## Bug description

VSCode has added some of the functionality from the Flutter extension by default and that has been removed from the extension itself. 

## To Reproduce

Outdated commands:
flutter.profileApp
flutter.openTimeline
all dart testing commands

## Expected behavior

The commands should work

## Additional context

I originally added the Flutter commands 3 years ago and will open a PR once I finish this issue.

**Comment by MarcoIeni** [comment]
pr welcome 👍

**Comment by PatrickWulfe** [comment]
I have an updated PR now that I was able to run sort-bindings and prettier, thanks!
