### ISSUE TITLE
Support the debugger commands like the gdb does.

### ISSUE THREAD

**Issue by yssource** [VSpaceCode/VSpaceCode#359]
Please to support the following commands, after starting the debug mode.

- `n` debug next
- `i`  step into
- `o` step out
- `c` continue
- `b` breakpoint
- `u` unbreakpoint
- `p` print the value of a variable
- `r` re-run
- `f` finish

... and some of others commands, which like what GDB does. 

Thanks.

**Comment by stevenguh** [comment]
I think we have most of these in `SPC d` already except

```
- `u` unbreakpoint
- `p` print the value of a variable
- `r` re-run
- `f` finish
```

You can also use the override to update to your preference.

**Comment by yssource** [comment]
Thanks.
I tried the python debugging, it seems I have to repeat `SPC d s`, `SPC d s`, `SPC d s` each step.
Is it possible to support the **transient mode** after launching the debugging?
For example, only `n`, for the next step, No `SPC d` repeated each time.

**Comment by stevenguh** [comment]
I think this is duplicate https://github.com/VSpaceCode/vscode-which-key/issues/72. Setting `debug.focusEditorOnBreak` may help.
