### ISSUE TITLE
update leader tab keybinding

### ISSUE THREAD

**Issue by ishovkun** [VSpaceCode/VSpaceCode#37]
quickOpenPreviousRecentlyUsedEditorInGroup

Need to update the leader, tab keybinding as follows:
```
        {
            "before": [ "<leader>", "<tab>" ],
            "after": [],
            "commands": [
                {
                    "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
                    "args": []
                }
            ]
        },
```

See the update https://code.visualstudio.com/updates/v1_42

**Comment by StreakyCobra** [comment]
Hi :) Neither the actual behavior nor the function you propose really mimics spacemacs `SPC TAB` functionality that alternates between buffers. But let's try to change to the function you suggest. If people complain we would probably revert that though.

dd69e4381ae76f2b1a630f619a40aef88d13c517

**Comment by i-am-the-slime** [comment]
@StreakyCobra This is a major source of pain for me. In spacemacs it feels very logical but here it just seems to randomly jump anywhere. Is there a way to mimic the spacemacs behaviour? I guess it would mean keeping track of some kind of history.

**Comment by StreakyCobra** [comment]
@i-am-the-slime The project has changed quite a lot recently (see https://github.com/VSpaceCode/VSpaceCode#project-history). I would suggest to open a new issue explaining your problem so new maintainers will see it :)
