### ISSUE TITLE
delete vim fork

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#42]
Should we delete [this](https://github.com/VSpaceCode/Vim) repo?
I don't think it's used anymore.
Apparently I don't have the permissions to that.

**Comment by StreakyCobra** [comment]
It was forked by someone who joined the project at the beginning but had since deleted his account, see https://github.com/VSpaceCode/VSpaceCode/issues/1#issuecomment-302352952 for details.

No commit had been made there, so it's useless for now. It's gone :coffin:
