### ISSUE TITLE
SPC s P does not work

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#44]
When I type `SPC s P` I get the error:
```
TaskQueue: Error running task. Failed to handle key=P. command 'workbench.action.findInFilesWithSelectedText' not found.
```
Was the action `workbench.action.findInFilesWithSelectedText` removed?
I don't see it when I press `SPC h d`.

If the action has been removed we can delete `SPC s P`.

**Comment by StreakyCobra** [comment]
https://github.com/microsoft/vscode/issues/44609#issue-300679362

> as was the case with workbench.action.findInFilesWithSelectedText which was removed in latest version
