### ISSUE TITLE
Which key: evaluate Spacecode project

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#45]
We should definitely take a look at [this](https://github.com/stevenguh/spacecode) project.
Maybe we could integrate it, migrate to it, merge the two projects..I don't know, I haven't tried it yet :)

**Comment by MarcoIeni** [comment]
I evaluated it and it looks great.
For example, for this settings.json file:
```
{
    "spacecode.bindings":[
       {
          "key":"f",
          "name":"File...",
          "type":"bindings",
          "bindings":[
             {
                "key":"n",
                "name":"New Untitled",
                "type":"command",
                "command":"workbench.action.files.newUntitledFile"
             },
             {
                "key":"i",
                "name":"Indentation...",
                "type":"bindings",
                "bindings":[
                   {
                      "key":"i",
                      "name":"Change indentation",
                      "type":"command",
                      "command":"changeEditorIndentation"
                   },
                   {
                      "key":"d",
                      "name":"Detect indentation",
                      "type":"command",
                      "command":"editor.action.detectIndentation"
                   },
                   {
                      "key":"r",
                      "name":"Reindent",
                      "type":"command",
                      "command":"editor.action.reindentlines"
                   },
                   {
                      "key":"R",
                      "name":"Reindent selected",
                      "type":"command",
                      "command":"editor.action.reindentselectedlines"
                   },
                   {
                      "key":"t",
                      "name":"Convert indentation to tabs",
                      "type":"command",
                      "command":"editor.action.indentationToTabs"
                   },
                   {
                      "key":"s",
                      "name":"Convert indentation to spaces",
                      "type":"command",
                      "command":"editor.action.indentationToSpaces"
                   }
                ]
             }
          ]
       },
       {
          "key":"t",
          "name":"Toggles...",
          "type":"bindings",
          "bindings":[
             {
                "key":"f",
                "name":"Toggle fold",
                "type":"command",
                "command":"editor.toggleFold"
             },
             {
                "key":"c",
                "name":"Toggle find case sensitive",
                "type":"command",
                "command":"toggleFindCaseSensitive"
             },
             {
                "key":"w",
                "name":"Toggle ignore trim whitespace in diff",
                "type":"command",
                "command":"toggle.diff.ignoreTrimWhitespace"
             },
             {
                "key":"W",
                "name":"Toggle word wrap",
                "type":"command",
                "command":"editor.action.toggleWordWrap"
             },
             {
                "key":"b",
                "name":"Toggle side bar visbility",
                "type":"command",
                "command":"workbench.action.toggleSidebarVisibility"
             },
             {
                "key":"j",
                "name":"Toggle panel visbility",
                "type":"command",
                "command":"workbench.action.togglePanel"
             },
             {
                "key":"m",
                "name":"Toggle maximized panel",
                "type":"command",
                "command":"workbench.action.toggleMaximizedPanel"
             },
             {
                "key":"t",
                "name":"Toggle tab visibility",
                "type":"command",
                "command":"workbench.action.toggleTabsVisibility"
             },
             {
                "key":"z",
                "name":"Toggle zen mode",
                "type":"command",
                "command":"workbench.action.toggleZenMode"
             }
          ]
       },
       {
          "key":"s",
          "name":"Show...",
          "type":"bindings",
          "bindings":[
             {
                "key":"e",
                "name":"Show explorer",
                "type":"command",
                "command":"workbench.view.explorer"
             },
             {
                "key":"s",
                "name":"Show search",
                "type":"command",
                "command":"workbench.view.search"
             }
          ]
       },
       {
          "key":"w",
          "name":"Window...",
          "type":"bindings",
          "bindings":[
             {
                "key":"w",
                "name":"Toggle editor group",
                "type":"command",
                "command":"workbench.action.navigateEditorGroups"
             },
             {
                "key":"-",
                "name":"Split editor below",
                "type":"command",
                "command":"workbench.action.splitEditorOrthogonal"
             },
             {
                "key":"\\",
                "name":"Split editor right",
                "type":"command",
                "command":"workbench.action.splitEditor"
             },
             {
                "key":"h",
                "name":"Move editor left",
                "type":"command",
                "command":"workbench.action.moveEditorToLeftGroup"
             },
             {
                "key":"j",
                "name":"Move editor down",
                "type":"command",
                "command":"workbench.action.moveEditorToBelowGroup"
             },
             {
                "key":"k",
                "name":"Move editor up",
                "type":"command",
                "command":"workbench.action.moveEditorToAboveGroup"
             },
             {
                "key":"l",
                "name":"Move editor right",
                "type":"command",
                "command":"workbench.action.moveEditorToRightGroup"
             }
          ]
       }
    ]
 }
```

This is what I get:
![Peek 2020-05-23 19-08](https://user-images.githubusercontent.com/11428655/82736289-cce47b80-9d28-11ea-8014-3845dcfa8aa2.gif)

**Comment by MarcoIeni** [comment]
With the new release it supports incremental edit. So your `settings.json` will only contain difference with the default key bindings. In the above example I defined all the key bindings in order to customize them, but now it isn't required anymore.

Anyway, I think we should take a decision and close this issue.

Since the two project have the same goal, there are different possibilities that comes to my mind:
1. The two repositories are merged into one, either this one or the other one. This one might be better since it has more stars and SEO.
2. In this repositoriy we define the key bindings and the other one becomes just a library that let other people define default key bindings. I don't know if it is technically possible.
3. The only difference between the two repository is that this repository has stuff like [default settings](https://github.com/VSpaceCode/VSpaceCode/blob/c63380c5fac9690909966a6d53b386cc6a954cde/settings.json#L431) or [keys](https://github.com/VSpaceCode/VSpaceCode/blob/master/keybindings.json), therefore this repository could focus on merging together pieces that bring the whole spacemacs experience (like other plugins and so on), while the other repository will focus only on the which-key and general key bindings. So this repository will link to the other one and we will delete the key bindings here.
4. Everything remains as it is and we pretend that nothing happened :cry: 

@StreakyCobra and stevenguh, do you have other options in mind? Which options do you prefer?
I would love to hear the opinion of other users, too!

Personally I think that number 2 is the best if it's feasible. Otherwise 1 or 3 are fine, too. I just hope that we don't duplicate the key bindings part into each other repository ^^'
Current duplication: [this](https://github.com/VSpaceCode/VSpaceCode/blob/master/keybindings.json), [other](https://github.com/stevenguh/spacecode/blob/adb5328639d39494d4378658261b833f244ef550/package.json#L59).

**Comment by StreakyCobra** [comment]
I can not give you definitive answers, but I can give you some food for thoughts.

Spacemacs is already a niche community, and people using Spacemacs' bindings in VSCode are even less numerous. If we want a good solution it would be far better to share the efforts, there is not much sense to split this small community.

If @stevenguh is open to merge the project that would be awesome. I guess it would be better to go for VSpaceCode name in the sense it is already a repository/organization that is not tight to one person and it also has more stars. If so I will obviously give him owner right on the organization and we can write a history section in the README to explain where the project comes from. I would also understand if he wants to continue his project under his name though :slightly_smiling_face:

So solution 1 would be the best for the community if it can happen. The solution 2 does not really makes sense for me because if the goal is really a collaboration, then it is better to all be on the same project, aka solution 1. Then between 3 and 4 I don't know if there is a solution that is better than the other. At the end you are the maintainer so that will be you call according on what you want to do for the future in this project :blush:

**Comment by MarcoIeni** [comment]
> The solution 2 does not really makes sense for me because if the goal is really a collaboration, then it is better to all be on the same project

Maybe I like creating libraries and splitting responsibilities too much :rofl:
Anyway, it's up to Steven personal preference :smile: 

For sure solution 2 must be taken into consideration only if the user experience remains as good as the spacecode extension one, i.e. you install a couple of extension and you are ready to go.

**Comment by stevenguh** [comment]
You guys have some really good points. Spacemacs for VSCode is definitely a niche community, and this repo does have bigger community to it. I think my ideal solution is somewhere between the 1 and 2.

I would like to break the spacecode repo into two repo. One is pure functional that only provide the menu structure only (`vscode-which-key`), and the spacecode (integrated to this repo or not) that contains bindings that are opinionated and bundled (using the [extension pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) feature of vscode extension) other extensions like edamagit, and vscode-advanced-open-file to provide the best out of the box experience on extension installation with one install click. However, there is still some engineering work figure out how the breaking up works.

About the integration, I am open to integrating as it would benefit the community; however, I have some concerns in how it works with all the details.
- How to migrate users from one extensions to another?
- How to migrate the existing users of this repo to the new system?
- There are some differences that current implementation of this repo is provide are not replicable in my repo (see below)

Also, some key bindings in this repo are not able to replicate with the quick menu in my implementation.
- Any key bindings with `TAB`
- Any key bindings that trigger Vim command like easymotion jump (We might able ask/provide a command binding in the upstream Vim repo)
- Any key bindings with modifier like `control`, `alt`

**Comment by StreakyCobra** [comment]
It seems that your both are willing to go in the direction of 2, that would be cool :blush: 

I want to propose you to host your extension repository on the `VSpaceCode` organization it that's an option for you. This will make easier for users to understand this is part of the same effort to bring Spacemacs to VSCode and not 2 different options to choose from.

---

> How to migrate users from one extensions to another?

I don't know all implications on this, but my gut feeling is: if that the direction you want to take, the sooner to move the better, as there will be less users concerned. Here we can write in the README about the direction of the project. On your side you can do the same, or maybe have a popup message in your current extension that it has moved?

> How to migrate the existing users of this repo to the new system?

For now we just have some settings copy/pasted manually in `settings.json`, so the migrations will be simple: remove the config and follow the new installation procedure. We can document this in the README. We have no way to contact the current users, but more and more users will migrate with time when they will see the new version :) And nothing will break anyway if they are happy with their current setup

> There are some differences that current implementation of this repo is provide are not replicable in my repo (see below)

I think nothing is definitive, the project can evolve. If there are some concessions we have to make to use your extension, be it. Maybe some bindings can't be ported right away, but I'm sure with time some solutions will be found. Also if users are not happy with the change, they can still hold to the current `settings.json` we propose.

**Comment by MarcoIeni** [comment]
> I would like to break the spacecode repo into two repo. One is pure functional that only provide the menu structure only (vscode-which-key), and the spacecode (integrated to this repo or not) that contains bindings that are opinionated and bundled (using the extension pack feature of vscode extension) other extensions like edamagit, and vscode-advanced-open-file to provide the best out of the box experience on extension installation with one install click. 

So this repo will become an extension pack, which bundles together a lot of plugins to replicate spacemacs experience, while you repo becomes the which-key plugin. It seems perfect to me :)

> How to migrate users from one extensions to another?
How to migrate the existing users of this repo to the new system?

Just update the README with the new installation instructions.

> some key bindings in this repo are not able to replicate with the quick menu in my implementation.

No problem, if something is not possible to be integrated in which-key it will remain as a VSCodeVim binding. Even if it will be not listed in which-key is not a problem at the moment.

> Also if users are not happy with the change, they can still hold to the current settings.json we propose.

Yeah, maybe we can maintain the current `settings.json` in a different branch, we'll see.

> the only concern I have is that maybe the other repo doesn't know how to distinguish between vim modes (normal, insert, visual, ..), but I am not sure.

What about this Steven? Is your plugin able to distinguish vim modes?

**Comment by stevenguh** [comment]
Since this repo only contains the manual installation steps. The migration step for the existing users of this repo is when they when visit again, they will read the readme.

---

> they can still hold to the current settings.json we propose.

> Yeah, maybe we can maintain the current settings.json in a different branch, we'll see.

We can probably tag the commit, so people can go back to look at them if they want

> What about this Steven? Is your plugin able to distinguish vim modes?

Technically it could with more work, but I thought the which key doesn't distinguish vim modes. Also a lot of commands are doing things automatically base on if it is visual or normal mode already, so I don't see it being super critical at the moment.

> So this repo will become an extension pack, which bundles together a lot of plugins to replicate spacemacs experience, while you repo becomes the which-key plugin. It seems perfect to me :)

This is the idea; however, there are many variations in this and stage. I will rank by the least number of moving parts.

1. Simple repo transfer to VSpaceCode org
    * This will keep two repos in the same org that offers different implementation
    * The existing publisher id of the extension and name wouldn't change (`stevenguh.spacecode`)
    * Reuse existing deployment of the extension
    * The existing users of `spacecode` wouldn't be affected
    * The `VSpaceCode/VSpaceCode` will redirect to `VSpaceCode/spacecode`
    * `which-key` break up and extension bundling will come later

2. Merge `develop` of `spacecode` to `VSpaceCode` org and reuse old extension id
    * This is merge the branches in `spacecode` to `VSpaceCode`
    * Transfer the issues in `spacecode` to `VSpaceCode`
    * The existing publisher id of the extension and name wouldn't change (`stevenguh.spacecode`)
    * Reuse existing deployment of the extension
    * The existing users of `spacecode` wouldn't be affected, this is a simple repo hosting shift
    * `which-key` break up and extension bundling will come later
    * By reusing the same extension name and id, `stevenguh.space` repo can be renamed to house the `vscode-alt-key` with a new extension id

2. Merge `develop` of `spacecode` to `VSpaceCode` org and start new extension id
    * This is merge the branches in `spacecode` to `VSpaceCode`
    * Transfer the issues in `spacecode` to `VSpaceCode`
    * Start a new deployment of the extension host in `VSpaceCode` with new publisher id and extension name (I can set that up)
    * Bump a version in `spacecode` to include a function to send a notification on start to ask people to migrate
    * Existing user of `spacecode` will need to manually reinstall
    * `which-key` break up will be in another repo other than `spacecode` and extension bundling will come later
    * `spacecode` repo will be achieved
    * The eventual `which-key` will live in a new repo.

If I had to rank of favorite solutions, it would be 2 > 3 > 1. Solution 2 has minimal disruption to the current users while transferring the code hosting to this repo which has a larger community. Solution 3 has some disruptions to the existing user, but I would say that's manageable. Solution 1 is not so different than what we have today so it's my least favorite.

**Comment by StreakyCobra** [comment]
If I understand correctly the main difference between 2 and 3 is whether to keep the publisher id/extension name or make a new one.

Personally I would go for 3 because:
- Having a publisher id/extension name that matches the project is less confusing for the users who will have to find and install it. That will also make the project looks more "serious".
- Doing it now will impact at most ~135 users, doing it in the future will become more and more difficult.
- If at some point you want to retire from the development, either:
    - you don't want that they use your name anymore and they will have to make users to move to another extension, what is complicated (see 2nd point above); or
    - your let them continue to use your name, but then you don't know what the community will do in the future and you may not want your name associated with the direction they may take. (Note that's also why I made an organization out of this project at the beginning instead of putting it under my name :slightly_smiling_face:)

But I can also understand that you want to keep your name associated with the extension and that you don't want to annoy your current users. So I would say that 3 is the best solution for me because of the points cited above, but if that's a no-go for you I think 2 is still better for the community than not making the merge.

**Comment by stevenguh** [comment]
I think 3 is probably better in a long run to bite the bullet now. How do you want to proceed this?
I would imagine the steps are as follow:
- I will be assigned the necessary rights to this repo and org
- I will push the `master` branch of `spacecode` to here as `spacecode` branch and all the tags
- I will make necessary changes here in `VSpaceCode/spacecode` to setup all the right name publisher and stuff
- I will setup all the org stuff in Azure in order publish new extension under VSpaceCode org (Apparently, I was trying things out azure created an org for me already. oh well. I can add your guys in the org)
- Publish the VSpaceCode extension as `v0.3.2`
- Merge `spacecode` branch to master
- Bump `stevenguh/spacecode` to `v0.3.3` to include a notification
- Achieve `stevenguh/spacecode`
- Get ready for `v0.4.0` which includes many more features and a more complete bindings

**Comment by StreakyCobra** [comment]
Sounds good to me :ok_hand: I'm just waiting for the approval of @MarcoIeni because he is officially the maintainer of this project (I'm mostly acting as gate keeper now, waiting for the project to be mature enough to fly on its own :smile:). Then I'll give both you and @MarcoIeni owner access to the organization.

In the README we can list @stevenguh and @StreakyCobra as authors, with eventually a small explanation about the merge if needed, and @stevenguh and @MarcoIeni as maintainers :)

Then I'm pretty sure you will figure out what is the best for this project :blush: And if you need someone to discuss anything project related I'll be around.

**Comment by MarcoIeni** [comment]
Yes, for me it's ok! We can discuss the details later

> We can probably tag the commit, so people can go back to look at them if they want

With a tag the code is fixed and that's it. Instead, I will create a branch in order to continue to maintain the `settings.json` file. We'll see :)

**Comment by stevenguh** [comment]
> With a tag the code is fixed and that's it. Instead, I created a branch in order to continue to maintain the settings.json file. We'll see :)

That makes sense

---

Thanks guys :)
spacecode branch is created, and I just updated the `package.json` with the new name. One question I have is do we go by `VSpaceCode/VSpaceCode` or keep using the extension current name, so it will be `VSpaceCode/spacecode`. I like the latter a little bit more and it's like `vscodevim/vim`.
If we go by the first, we probably should change all the configuration and command ids. For example:
`spacecode.space` -> `VSpaceCode.space`
`spacecode.bindings` -> `VSpaceCode.bindings`

**Comment by MarcoIeni** [comment]
I wouldn't rename the repository

**Comment by StreakyCobra** [comment]
I don't have a strong opinion on this. The question is what are the pros/cons and implications of both solutions. I'll let you two discuss about that, but if you need a tie breaker I can help :)

**Comment by stevenguh** [comment]
Okay. I think the name of config and the command id can stay, and just changing the name of the repo that would also help existing user migrate.

**Comment by stevenguh** [comment]
Apparently, the current `name` used in the `package.json` is in violation of the schema. It shouldn't any contain capital case. Should I fall back to `vspacecode` or `spacecode`? This is likely be used to uniquely identify the package in vscode extension marketplace.
Note that it won't affect the display name since because there is `displayName` for that.

**Comment by MarcoIeni** [comment]
So we use vspacecode as id and this repository name on github remains unchanged? Ok

**Comment by stevenguh** [comment]
I think the `spacecode` branch is ready to publish as an extension -- I have all the pipeline setup and ready to go (let me know if you want to setup to publish as well, I can add you to the azure devop and the vs marketplace thing)
- All references of Spacecode are renamed to VSpaceCode
- All the references of `spacecode` like the prefix of the commands and the extension id (`name` in the `package.json`) are renamed to `vspacecode`

The additional notification and migration update on the README is also ready on the `stevenguh/spacecode` in https://github.com/stevenguh/spacecode/compare/migration.
- Have a README that contains migration
- Add a vs notification on editor startup.

> So we use vspacecode as id and this repository name on github remains unchanged? Ok

Yes, that's correct. I am ready to publish🚀

**Comment by StreakyCobra** [comment]
Nice to see this energy :clap: Project is yours, proceed as you whish :blush:

**Comment by stevenguh** [comment]
Merged and published 🚀

**Comment by MarcoIeni** [comment]
> let me know if you want to setup to publish as well, I can add you to the azure devop and the vs marketplace thing

maybe it would be nice to have a second account (like mine) for backup. What do you think about automatically deploying the new release of the plugin after each git tag?
It you agree we should open an issue about this.

**Comment by stevenguh** [comment]
> maybe it would be nice to have a second account (like mine) for backup. 

Let me know what email I should use for the invite? (the one in the commit message)

> What do you think about automatically deploying the new release of the plugin after each git tag?

That's a nice to have. I am not too bugged by it atm. Feel free to open an issue to track it, and add it to the roadmap as miscellaneous?

**Comment by MarcoIeni** [comment]
Yes, the one in the commit message (gmail) is fine.

> add it to the roadmap as miscellaneous?

It makes no sense to add miscellaneous issues to the roadmap to me. If they are in the issue tracker and they are not listed in the roadmap issue it is implied that they are miscellaneous :)

**Comment by stevenguh** [comment]
> Yes, the one in the commit message (gmail) is fine.

I added you to the azure devop; however, I can't add you to the marketplace. Maybe you need to register an account in the marketplace, or need to an ms account. I am not sure, I use a hotmail account for all these.
https://stackoverflow.com/questions/56032912/vs-marketplace-add-member-displayes-invalid-domain-error

> It makes no sense to add miscellaneous issues to the roadmap to me. If they are in the issue tracker and they are not listed in the roadmap issue it is implied that they are miscellaneous :)

That makes sense :)

**Comment by MarcoIeni** [comment]
I registered I think, can you try again?

**Comment by stevenguh** [comment]
It still doesn't work. Why don't you send your `vsid` to me and I will send that via the contact MS button and hopefully they can add it in manually.

**Comment by MarcoIeni** [comment]
> It still doesn't work. Why don't you send your vsid like the stackoverflow post to me and I will send that via the contact MS button and hopefully they can add it in manually.

For the record: we did this. I am the second owner of the VSpaceCode organization on https://marketplace.visualstudio.com/
