### ISSUE TITLE
Evaluate integration with vscode-advanced-open-file. 

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#46]
The gif of [this](https://github.com/jit-y/vscode-advanced-open-file) project has a behavior which is very similar to original spacemacs `SPC f f`.

You should evaluate this project in order to see if it exposes some actions which may be integrated in our [setting.json](https://github.com/VSpaceCode/VSpaceCode/blob/master/settings.json).

**Comment by stevenguh** [comment]
It works pretty well for me, although there is no `<TAB>` support. the search and enter key works very well. I am imaging the same menu structure could work well for folder opening, and I opened an issue to track that work https://github.com/jit-y/vscode-advanced-open-file/issues/24

Btw, there is a feature request on the vscode to support separate the command to open folder/files. This will be helpful in distinguishing `<spc> p p` and `<spc> f r`, show your support so the feature at least will get to backlog. https://github.com/microsoft/vscode/issues/100421

**Comment by stevenguh** [comment]
Another direction to support file/directory opening would be creating another extension that do something similar to edmagit that uses a buffer than we will have `<TAB>` support. Ultimately, I think the best solution would be somewhere between `vscode-advanced-open-file` and a custom buffer. However, that would require more engineering work.

**Comment by stevenguh** [comment]
I took this out of the `v0.5.0` as the extension doesn't have a folder opening feature. This seems heavy for something as simple as opening a file unless the extension also covers other file/folder opening features. There's a lot of edge cases needed to handle like opening local file in the vscode environment. For people who want to use that as your <spc> f f, you can bind it in your overrides.

Interesting, VS code remote has file opening prompt that's closer to what we need.

**Comment by stevenguh** [comment]
Closing this in favor of #65
