### ISSUE TITLE
automatically release plugin on every git tag

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#50]
Maybe with github actions? Or azure itself offers some support for this?

**Comment by stevenguh** [comment]
VS extension publish seems very clunky, and this needs investigation. It's *seems* like VScode/Vim project is manually publishing as well.

**Comment by stevenguh** [comment]
That's not true, apparently, they have a CI server setup.
Apparently, there is this github action https://github.com/marketplace/actions/github-action-for-vsce. However, a token will need to renew at max every year. Wonder is there a reminder feature in github to remain us to renew the token.

**Comment by MarcoIeni** [comment]
> Wonder is there a reminder feature in github to remain us to renew the token.

Cron jobs are supported. A cron job could:
- automatically renew it? :rofl: 
- run every week and fail if the certificate will expire in one month

**Comment by stevenguh** [comment]
The token is not a certificate, so we don't have a way to look at expiration from the string directly. I am thinking maybe like an email to notify a contributor to update the key stored in github.

**Comment by MarcoIeni** [comment]
> EDIT: Something like this? https://probot.github.io/apps/reminders/

Yes, it could be ok for the moment. I will set it up when the github action is there.

**Comment by stevenguh** [comment]
Just created a github action `deploy.yml`, and will test that out on Monday.

Maybe a corn job that creates an issue might be better like https://github.com/marketplace/actions/create-an-issue and assign that created issue to me. The current token is set to expired on 2021-06-20.

**Comment by MarcoIeni** [comment]
> Maybe a corn job that creates an issue might be better like https://github.com/marketplace/actions/create-an-issue and assign that created issue to me. The current token is set to expired on 2021-06-20.

Yes, I will do it. Once I do it this issue will be closed.

**Comment by stevenguh** [comment]
Thanks 😊

**Comment by MarcoIeni** [comment]
@stevenguh close this issue if you think that the action added in bc940e4 is ok. We will see 1 January if it works. ^^'

**Comment by stevenguh** [comment]
Looks good. Thank you :)
