### ISSUE TITLE
Bind SPC s s to fuzzySearch to emulate Helm Swoop / Ivy Swiper

### ISSUE THREAD

**Issue by RyanGreenup** [VSpaceCode/VSpaceCode#56]
Providing a binding for some replacement to Helm-Swoop/Ivy-Swiper bound to <kbd>SPC</kbd><kbd>s</kbd><kbd>s</kbd> would be really nice, Using the [fuzzy-search](https://marketplace.visualstudio.com/items?itemName=jacobdufault.fuzzy-search) extension I've put the following in my `settings.json` to emulate it:

```js   
 {
  "before": ["<leader>", "s", "s"],
  "commands": ["fuzzySearch.activeTextEditor"]
  },
```

Maybe this is something that could be included out of the box?

<details><summary>Extension Details</summary>
<p>

Name: fuzzy-search
Id: jacobdufault.fuzzy-search
Description: Fuzzy search
Version: 0.0.2
Publisher: jacobdufault
VS Marketplace Link: [https://marketplace.visualstudio.com/items?itemName=jacobdufault.fuzzy-search](https://marketplace.visualstudio.com/items?itemName=jacobdufault.fuzzy-search)

</p>
</details>

**Comment by stevenguh** [comment]
That's very close to `<spc> s s` and I think this would be a great candidate for `v0.5.0`. After `v0.4.0` is released on Monday, you can add this behavior by using overrides like
```json
{
  "vspacecode.bindingOverrides": [
    {
      "keys": "s.s",
      "name": "Fuzzy search activate text",
      "type": "command",
      "command":"fuzzySearch.activeTextEditor",
    }
  ]
}
```

**Comment by stevenguh** [comment]
Added to develop and set to release for `v0.5.0`
