### ISSUE TITLE
Re-eval installation method

### ISSUE THREAD

**Issue by stevenguh** [VSpaceCode/VSpaceCode#57]
Currently, we have a vscode notification to guide use to install settings automatically; however, there are some cases that it currently needs to be worked on. For example: vscode remote. Also, there is no api for extension to add to user's `keybindings.json`, although there is a hack that could.

Moving forward, a question remains -- what if we cannot automate well on installation, should we switch to a fully manual installation like copy-and-paste?

There are a few options:
1. Continue the current installation method of adding config automatically to user's `settings.json` when user click the button in the notification.
2. Remove the continuous checking. Only check on a fresh install.
3. Remove notification on fresh install, and only provide command to install. For example, the user will need to use `Ctl+Shift+P` to install.
4. Completely manual

There's also a lot of moving parts that would change the consideration on this like dropping support of non-vim users, support `y` menu in magit (which will need to add bindings to user's `keybindings.json`)

My current thinking is that, the continuous checker will likely to be removed because when we add `<spc> j` we will requires user to enable easy motion; however, user might not want to enable that. So continuous checker can be an annoyance when the user turned some settings off. This is open to discussion.

**Comment by MarcoIeni** [comment]
> the continuous checker will likely to be removed because when we add <spc> j we will requires user to enable easy motion; however, user might not want to enable that.

1. We specify in the docs (the markdown table that needs to be done) that `spc j` depends on a plugin, so user are not surprised if it does not work
2. If the action is not available the key is not showed (is it possible?) 
3. We specify in the config that this key depends on some plugin. If that plugin is not installed the key is not showed

**Comment by stevenguh** [comment]
I'd think document is always good to have. I think for the rest of the options, they are a little bit technological challenged and the UX of magically hiding something in the configuration is a little bit weird.

**Comment by MarcoIeni** [comment]
Ok, so no options 2 and 3 at the moment.

Anyway, automatically adding stuff to settings.json is nice if we make it clear in the installation process, while copy pasting is not fun. In v0.4.0 the process is not that bad :)

> Remove the continuous checking. Only check on a fresh install.

What about setting a flag in settings.json that says that the installation has been done. If the user wants to do the installation again, he could remove this flag from settings.
Spacemacs does an installation too if there is no .spacemacs file, so our behaviour could be similar.

**Comment by stevenguh** [comment]
Just an update on the installation method.
- Implemented an automatic `keybinding.json` updating
- Removed the continuous setting checker for now
- Add three commands that's accessible from `Ctl+Shift+P` to config default settings and keybindings needed for VSpaceCode.

Work is still in progress
- Refactor the settings update, so we can have a `settings.json` in the repo for easy setting adding also easy for us to point out what are the basic settings that we required for default config.

> Anyway, automatically adding stuff to settings.json is nice if we make it clear in the installation process, while copy pasting is not fun. In v0.4.0 the process is not that bad :)

Base on the update above, we are able to retain the function to install necessary config one one button on fresh installation of the installation. I also added the command access for people that wanted "reinstall" those configurations. Does that sound good to you?

> What about setting a flag in settings.json that says that the installation has been done. If the user wants to do the installation again, he could remove this flag from settings.
Spacemacs does an installation too if there is no .spacemacs file, so our behaviour could be similar.

That's an interesting idea; however, I think in practice it's similar to continue checking because there's no one file to check if the user's installed. There are a lot of edge cases that I want to opt for a simpler model for now. Do you think that the initial installation notification on fresh install and the additional commands accessible with `Ctl+Shift+P` to "reinstall" configurations would be okay for 90% users for now?

**Comment by MarcoIeni** [comment]
> Refactor the settings update, so we can have a settings.json in the repo for easy setting adding also easy for us to point out what are the basic settings that we required for default config

So here we can set default settings that could be changed by the user in its own config? For example here we can enable easy motion?

Anyway, the rest sounds really good to me!

**Comment by stevenguh** [comment]
yes 😊

**Comment by MarcoIeni** [comment]
Great! We should make this clear in the README, in this way people know what's enabled by default and they can disable it if they want

**Comment by stevenguh** [comment]
I updated the README in develop. Feel free to edit it if that's not clear.
