### ISSUE TITLE
Configure delay between typing the command and the menu showing up

### ISSUE THREAD

**Issue by peey** [VSpaceCode/VSpaceCode#68]
In spacemacs, the minibuffer with command hints shows up with a delay.

This has the benefit that if you have the command memorized, you don't need a janky ui part momentarily appearing then disappearing. 

Example scenario: I don't want the menu to show up every time I'm switching between open panes using `SPC w h` and `SPC w l`

**Comment by stevenguh** [comment]
A delay is implemented (See #55). The instruction will be updated on README along with `v0.6.0` release. However, an input box from the QuickPick is still needed. Use `vscode-vim` branch, if you don't want an input box at all.

**Comment by peey** [comment]
Thanks! Closing this as a duplicate.
