### ISSUE TITLE
Commands in the README do not exist

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#70]
The commands from the [configuration](https://github.com/VSpaceCode/VSpaceCode#configuration) section of the README do not exists.
This is what I have in v0.6.0

![image](https://user-images.githubusercontent.com/11428655/87706629-1d63dc80-c7a0-11ea-864a-b4ff61d172bc.png)

As you can see the names are different.

Should I just rename the commands in the readme with the first 3 of the picture?

**Comment by stevenguh** [comment]
Ahhh...forgot to update that part. Will fix that soon.

**Comment by stevenguh** [comment]
I am sorry, I didn't realize you asked a question. This should be fixed now. Thanks :)
