### ISSUE TITLE
Restore <SPC> <TAB> to switch to previous editor

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#71]
`SPC <tab>` works with the following `settings.json`:

```
{
    "vim.normalModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<space>"
            ],
            "commands": [
                "vspacecode.space"
            ]
        },
        {
            "before": ["<leader>", "<tab>"],
            "commands": ["workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"]
        },
    ],
    "vim.visualModeKeyBindingsNonRecursive": [
        {
            "before": [
                "<space>"
            ],
            "commands": [
                "vspacecode.space"
            ]
        }
    ],
}
```

Of course it is an hack and this key bindings will not be listed in which key.

What do you think? In my opinion this key binding is really useful, so maybe this hack may be worth it.
We could specify that this key binding is not showed in which key in the file that we discussed in #47 

This issue is related to #52

**Comment by stevenguh** [comment]
Is https://github.com/VSpaceCode/VSpaceCode/blob/v0.6.0/package.json#L117-L125 not doing what you are requesting?

**Comment by MarcoIeni** [comment]
sorry, completely missed it ^^'
