### ISSUE TITLE
Make `SPC f t` close the explorer sidebar if it's visible

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#79]
Quoting VSpaceCode/vscode-which-key/issues/5, Spacemacs `SPC f t` chord does the following:

> 1. If the sidebar isn't open, open the sidebar and focus the explorer.
> 2. If the sidebar is open but the explorer is not visible, open the explorer and focus it.
> 3. If the sidebar is open and the explorer is visible, close it.

Currently, `SPC f t` does 1 and 2, but not 3. I just double-checked to make sure, and Spacemacs definitely does number 3, but VSpaceCode's implementation of it does not. This should be added to VSpaceCode.

**Comment by stevenguh** [comment]
Added `which key` label, because this is likely to be infrastructure improvement in `which key`, which is to execute command base on `when` like `keybindings.json`, unless there is way to executing a simple command that's aware of visibility of sidebar and explorer.

**Comment by stevenguh** [comment]
Implemented in https://github.com/VSpaceCode/VSpaceCode/commit/f619617ac1cf427d8a99eaeb8ea8284c42690938

**Comment by macintacos** [comment]
Whoa, conditional bindings 🤯 can't wait for that to not be "experimental" anymore 😅
