### ISSUE TITLE
My (very custom) keybinding setup; just wanted to share

### ISSUE THREAD

**Issue by macintacos** [VSpaceCode/VSpaceCode#80]
I spent a bunch of time adding a lot of new menus/commands to my default VSpaceCode setup, which I've put up in a gist here:

https://gist.github.com/macintacos/d63b7057cee0638e7ccfcdd6d1b7f662

Feel free to rip as much as you'd like.

I don't think that I necessarily want to contribute this directly to this repo, since there are a lot of opinionated menus/actions that I added that deviate from "traditional" Spacemacs. One _big_ thing that I did (for example) is that I remove all references to magit; while I really like magit, I've gotten used to my workflow with Sublime Merge over the past year or so, and that's by far the most opinionated thing in there. There are also a lot of references to extension commands that naturally you'd have to have installed in order for them to work.

The biggest thing that made me realize that I could use VSpaceCode for everything was when I saw which-key and the fact that you could map `<space>` to invoke VSpaceCode directly (meaning that you could theoretically invoke it from anywhere, not just the editor), so now I can completely move away from Spacemacs to VSCode with really minimal compromises for my needs. Thanks a bunch; I'll probably deprecate [Chord Heavy](https://marketplace.visualstudio.com/items?itemName=vscode-macintacos.chord-heavy-keymap) and just point them to this extension.

**Comment by stevenguh** [comment]
There are some interesting commands that might be applicable to the general users especially the major mode since there are some built-in extension bundled with vscode like markdown, and notebook stuff.

I am thinking

1. Rip parts of it that make sense to general public
2. Maybe have another repo to store other user's configurations?

@MarcoIeni What do you think?

**Comment by MarcoIeni** [comment]
> I don't think that I necessarily want to contribute this directly to this repo, since there are a lot of opinionated menus/actions that I added that deviate from "traditional" Spacemacs.

I agree with point 1 of steven. We don't eat people who propose bindings we don't like :) I propose you to do different pull requests on each group of key bindings, so we can discuss them better.

Otherwise I will just copy paste and do commits under my name but I don't think is that nice.

> There are also a lot of references to extension commands that naturally you'd have to have installed in order for them to work.

We can add them.

I also agree with point 2 of steven, we could have another repo under this organization called something like "community-config" in which we collect alternative key bindings.

**Comment by macintacos** [comment]
@stevenguh to answer your question, yes, I have mapped `SPC` directly exactly the way you described instead of some other keybinding, and have only run into issues with text fields not "leaving" focus properly; which IMO is quite minor. If there were a VSCode command to "always leave focus" when hitting `ESC` or something similar, then mapping VSpaceCode's invocation to just `SPC` would work perfectly. This is partially why I opened the following issues:

- https://github.com/microsoft/vscode/issues/103728
- https://github.com/microsoft/vscode/issues/103845 (please vote/tell folks about this on, because honestly if this were added it'd definitely resolve the problem)

I was mostly able to get past this problem by setting up the following keybindings, but it's still not 100% perfect (but close enough for me to use as a daily driver now):

```
  {
    "key": "Escape",
    "command": "workbench.action.focusFirstEditorGroup",
    "when": "!editorTextFocus && !whichKeyActive && inputFocus && !terminalFocus"
  },
  {
    "key": "Escape",
    "command": "workbench.action.focusFirstEditorGroup",
    "when": "!editorTextFocus && !whichKeyActive && panelFocus && !terminalFocus"
  },
  {
    "key": "Escape",
    "command": "settings.action.focusSettingsFile",
    "when": "inSettingsSearch"
  },
  {
    "key": "escape",
    "command": "-settings.action.clearSearchResults",
    "when": "inSettingsSearch"
  },
  {
    "key": "shift+escape",
    "command": "workbench.action.focusFirstEditorGroup",
    "when": "terminalFocus"
  }
```

**Comment by stevenguh** [comment]
yeah, that's one of my problems with it as well. I am glad are you are addressing that `<esc>` issue since I hadn't gotten any time to play around with different `escape` shortcuts to de-focus.

**Comment by MarcoIeni** [comment]
@macintacos with respect to my previous message, do you plan to do some pull requests or should I commit the key bindings I like from your gist?
For me it's the same, up to you :)

**Comment by macintacos** [comment]
@MarcoIeni I think you might want to do this since a whole-sale rip of everything in my overrides might not be what you want to add for a general-purpose configuration for all users of VSpaceCode. I've actually modified it a little bit since I started this issues, so I'll get that updated (I'll drop a comment when I've pushed the revision)

**Comment by MarcoIeni** [comment]
Great, thanks.
Maybe after this merge we could update your configs in that "community config" repo we were talking about.

**Comment by macintacos** [comment]
Gist has been updated, also pointing to my multiCommands array that I set up for some other commands that my overrides are referencing (again, this is another external dependency so I'm not sure you want to include it).

Can you point me to the community config repo? I can probably more properly explain how I set up my config there if I had a folder to add the files to and a README for that folder 🙁

**Comment by MarcoIeni** [comment]
I just did it: https://github.com/VSpaceCode/community-configs
You can submit a pull request with your folder :)

Steven, if you have a better name for the repo we can change it.

**Comment by macintacos** [comment]
Awesome, putting it on my list of things to do this weekend!

**Comment by stevenguh** [comment]
Thank you for taking the lead on this :) Ideally, there will be some structures in the `community-configs` so when people contribute, there is somewhat a common format?
Another thing I am thinking is that since people can have their own bindings using either `VSpaceCode` or `vscode-which-key`, it's probably good to call out that some where in that format as well.

**Comment by macintacos** [comment]
If you'd like, we can figure out that format when I submit that PR and we can use that going forward, at least as a v0.0.1? 😅

**Comment by stevenguh** [comment]
Sounds good :) Thank you

**Comment by MarcoIeni** [comment]
I added a lot of key bindings. I reviewed them until ` "keys": "h.d",` (line 467).
A lot perfectly matched spacemacs original key bindings.

**Comment by macintacos** [comment]
Now that I sit down to do this, I'd like to see what gets added so that I can trim down what I contribute to that other repo. Can y'all let me know when you're done "harvesting" it?

This also brings to mind another question that I have; how will I know if a keybinding I've set is "redundant" because it's been added in the main config? Ideally I'd like to get rid of the ones that are added to VSpaceCode properly, and I think that that'd be a rather... tedious process that I brought upon myself 🙂. Although now that I think about it, that's probably a question for the vscode-which-key repo (maybe in https://github.com/VSpaceCode/vscode-which-key/issues/7?)

**Comment by stevenguh** [comment]
One of the questions I had but forgot to ask was, did you have any specific reason why you are not using `vspacecode.bindings` since your binding changes is so big? (so you changes will not be affected by any upstream stream changes)

Right now, the best bet is to check out the changelog unfortunately. If you used `vspacecode.bindings` option, then you can just ignore whatever changes that's happening on the default bindings.

**Comment by macintacos** [comment]
I initially started by wanting to supplement existing menus, but that transformed into occasionally adding new menus entirely. I was already using the `bindingsOverrides` which worked well enough, so I didn't consider what would happen had they been integrated into the "official" version.

If I'm honest, I don't _want_ to build a fully custom layout from scratch, which is partially why I presented my config to y'all to begin with. I knew that many of the chords that I added were straight from Spacemacs so I was hopeful that you'd add them and then I could remove them as releases came out.

As an aside, now that I fully read through all the bits of the README, I don't think I could tell you a point where I'd opt for using `vspacecode.bindings` over `vspacecode.bindingOverrides` personally. I think I'd welcome the friction of you all overriding my keybindings so that it forces me to re-think how I'm considering my own keybindings (especially pre-1.0). With `vspacecode.bindings` I could probably set them and forget that you all might be making changes that I won't even become aware of unless I look at the changelog or the code diff.

I don't mind doing this manual cleanup though, so no worries on that front.

**Comment by stevenguh** [comment]
> I initially started by wanting to supplement existing menus, but that transformed into occasionally adding new menus entirely. I was already using the `bindingsOverrides` which worked well enough, so I didn't consider what would happen had they been integrated into the "official" version.

> As an aside, now that I fully read through all the bits of the README, I don't think I could tell you a point where I'd opt for using `vspacecode.bindings` over `vspacecode.bindingOverrides` personally. I think I'd welcome the friction of you all overriding my keybindings so that it forces me to re-think how I'm considering my own keybindings (especially pre-1.0). With `vspacecode.bindings` I could probably set them and forget that you all might be making changes that I won't even become aware of unless I look at the changelog or the code diff.

That makes sense. I was just wondering how different options are being used in the wild, and make sure you know there's another option to setting up bindings.

> If I'm honest, I don't _want_ to build a fully custom layout from scratch, which is partially why I presented my config to y'all to begin with. I knew that many of the chords that I added were straight from Spacemacs so I was hopeful that you'd add them and then I could remove them as releases came out.

I think we are in the process of integrating, so your overrides ideally should be smaller eventually 🙂

**Comment by MarcoIeni** [comment]
> Can y'all let me know when you're done "harvesting" it?

Yes, I hope to finish reviewing your key bindings this month.

> how will I know if a keybinding I've set is "redundant" because it's been added in the main config? 

That's one of the reasons why submitting a pull request is preferred 😅

Anyway you could diff package.json file with a previous version and check manually what changed

**Comment by MarcoIeni** [comment]
Nevermind, I just finished reviewing all the key bindings. I left out a lot of key bindings that require an external extension like markdown or project manager.

I will not add language specific key bindings like python, go or markdown, since we don't have support for major mode, yet.
However, we could add markdown related key bindings to text group (SPC x) if we assume that nowadays text means markdown.

Anyway, it could be time to close this issue and to open new issues for each remaining point to be discussed, if any. Tell me if this is ok for you.

macintacos, if you have comments on my key bindings either open an issue, pull request or comment on the individual commits.

**Comment by stevenguh** [comment]
Thank you very much for working through all of the bindings🙂

Since markdown is shipped with vscode, we can safely assume the users will always have it and put them in major mode key bindings? As far as to major mode support, we need another issue to track it (probably in this repo).

**Comment by MarcoIeni** [comment]
> As far as to major mode support, we need another issue to track it (probably in this repo).

Opened #84

**Comment by MarcoIeni** [comment]
I close this, feel free to comment if there something more to say.

**Comment by anupam312nwd** [comment]
> I spent a bunch of time adding a lot of new menus/commands to my default VSpaceCode setup, which I've put up in a gist here:
> 
> https://gist.github.com/macintacos/d63b7057cee0638e7ccfcdd6d1b7f662
> 
> Feel free to rip as much as you'd like.
> 
> I don't think that I necessarily want to contribute this directly to this repo, since there are a lot of opinionated menus/actions that I added that deviate from "traditional" Spacemacs. One _big_ thing that I did (for example) is that I remove all references to magit; while I really like magit, I've gotten used to my workflow with Sublime Merge over the past year or so, and that's by far the most opinionated thing in there. There are also a lot of references to extension commands that naturally you'd have to have installed in order for them to work.
> 
> The biggest thing that made me realize that I could use VSpaceCode for everything was when I saw which-key and the fact that you could map `<space>` to invoke VSpaceCode directly (meaning that you could theoretically invoke it from anywhere, not just the editor), so now I can completely move away from Spacemacs to VSCode with really minimal compromises for my needs. Thanks a bunch; I'll probably deprecate [Chord Heavy](https://marketplace.visualstudio.com/items?itemName=vscode-macintacos.chord-heavy-keymap) and just point them to this extension.

Can someone explain how to use this file? Like where to store this file, and how to make changes in settings to use it? Thanks!

**Comment by macintacos** [comment]
You add this to your VSCode `settings.json` file. You should check VSpaceCode's documentation for more info. 

FWIW, I no longer maintain the gist, and I don't plan to resume maintenance. Feel free to steal whatever you'd like from it though, naturally.
