### ISSUE TITLE
Jump to word with fuzzy search

### ISSUE THREAD

**Issue by romainmartinez** [VSpaceCode/VSpaceCode#87]
First of all, congratulations on the latest update.

I really like `helm swoop` in spacemacs.
So I was pleasantly surprised by your implementation with fuzzy search (search in the current editor with `<spc s s>`).
Unfortunately, when I use it, the cursor is not positioned on the searched word but only at the beginning of the line containing the searched word.

Is there an option or other shortcut to access this feature?

**Comment by stevenguh** [comment]
We are using https://github.com/jacobdufault/vscode-fuzzy-search for `<spc> s s`, so I'd recommend opening an issue there or pull request (since it shouldn't be that hard to fix).

The other option is that we can find another extension to bundle for the fuzzy search function.

**Comment by romainmartinez** [comment]
Thanks. I posted an issue [#12](https://github.com/jacobdufault/vscode-fuzzy-search/issues/12)

**Comment by MarcoIeni** [comment]
I close this, since no action is left for us. Feel free to comment if you have something to add :)
