### ISSUE TITLE
SPC SPC does not work if typed too quickly

### ISSUE THREAD

**Issue by philipfeldmann** [VSpaceCode/VSpaceCode#91]
When using SPC SPC quickly, most of the time it doesn't recognize the second SPC but say "␣ is undefined". 
Usually I have to wait half a second between keystrokes, which feels clunky.

**Comment by stevenguh** [comment]
That's pretty weird. What's your environment/hardware? Try delayed menu and see if that would help (maybe it was the rendering of the menu and searching those menu that cause the pref issue)
Related: https://github.com/VSpaceCode/VSpaceCode/issues/55#issuecomment-649809410

**Comment by philipfeldmann** [comment]
@stevenguh Thanks for your suggestion. I've tried setting different delays by setting `"whichkey.delay"` in my settings, but it never seems to make any difference, no matter what I set it to.

**Comment by MarcoIeni** [comment]
Yes, even though setting "whichkey.delay" helped, I still experience some lag in the VM.
Is your pc old or you are coding inside a vm (in this case try [vscode remote](https://code.visualstudio.com/docs/remote/remote-overview))?

Anyway, I haven't written the javascript code of the extension, so Steven correct me if I'm wrong, but I believe that we are relying on VSCode APIs, so I don't believe there is anything that we can do to solve this issue.

If someone is aware of some possible optimizations I think that Steven will be very happy to hear that.

I am sorry, but the only solution that I am aware of is to use the [vscode-vim](https://github.com/VSpaceCode/VSpaceCode/tree/vscode-vim) branch, which relies on VSCodeVim only.

**Comment by stevenguh** [comment]
Yes. You are right that there are limited pref we can do, we are already caching all the menu items in memory. Also, vscode-remote is a great suggestion if your are running a VM (they also added support for Windows and Mac as remote server since I last checked).

The part that bugs me is the error message of "␣ is undefined". That doesn't sound right to me, and we would love to figure out a consistent repo for that. Some questions I would ask is:
- Platform? (Windows, Linux, Mac) in a VM?
- Rough specs?
- How do you trigger the the menu? from a text editor?
- Did you made any customization to VSpaceCode?

Meanwhile, I can try to do some profiling to see if we can see anything out of place.

**Comment by MarcoIeni** [comment]
Philip, in order to easily report your specs and environment, you can press `SPC SPC` and type "help report issue"

you should see something like this:

![image](https://user-images.githubusercontent.com/11428655/91484769-0f7a9e80-e8aa-11ea-84bb-62e50a37d0c7.png)

you can take a screenshot of it

**Comment by philipfeldmann** [comment]
I am having this issue both on my private machine (2019 mid-level 27" iMac) as well as my work place's machine (2018 15" macbook pro), both of them are running vscode directly on mac os, **I am not using a vm**. I'd like to think both machines are powerfull enough that this would be a performance issue.
Also what's weird is that this doesn't happen consistently. Sometimes it just works fine even when I smash the space bar in quick succession, other times it doesn't work even If I wait a full second between keystrokes.

<img width="916" alt="Screen Shot 2020-08-28 at 10 05 05" src="https://user-images.githubusercontent.com/6271103/91537217-3e2e5e80-e916-11ea-9b95-647c17233e91.png">
<img width="2177" alt="Screen Shot 2020-08-28 at 09 58 50" src="https://user-images.githubusercontent.com/6271103/91537206-3b336e00-e916-11ea-8bc0-4f83d9c2e913.png">
<img width="2180" alt="Screen Shot 2020-08-28 at 09 59 10" src="https://user-images.githubusercontent.com/6271103/91537218-3ec6f500-e916-11ea-8824-3a4fbf442f12.png">

**Comment by MarcoIeni** [comment]
> What is the difference between the master and the vscode-vim branch?

vscode-vim branch is not an extension, it is just a bunch of VSCodeVim [key bindings](https://github.com/VSpaceCode/VSpaceCode/blob/vscode-vim/settings.json) that you have to copy paste in your settings.json. It is the old approach used by this repo.

Pros:
- it is smoother

Cons:
- you loose the which key menu
- key bindings are not kept up to date with the master branch (help is well accepted!)

**Comment by stevenguh** [comment]
It doesn't seem like a spec issue. However, your screen did show that the error is `.␣ is undefined`, which means that you somehow were able to entered that key `.` in the input of QuickPick.

I can reproduce the same error message in the following two scenarios:
1.  You somehow bound the space in key to `. ` in the keybindings.json like the following
```json
{
    "key": "space",
    "command": "whichkey.triggerKey",
    "when": "whichkeyActive",
    "args": ". "
}
```
2. Somehow your system/keyboard entered `.` `<spc>` after your initial menu triggering. I can reproduce that by copy `. ` and pasted after the initial spacecode menu triggered.

**Comment by jackcasey** [comment]
I am also having this. It's weird. It seems to happen or not pretty randomly. And it seems to flip behaviour when you do 'stuff' like selecting text etc.

![whichkeybug](https://user-images.githubusercontent.com/45890/92088128-0a17d980-edff-11ea-9dac-422b73a8abad.gif)

Just noticed I misspelt "selecting" but I am not going to record that again :)

**Comment by jackcasey** [comment]
Ah Ha! 🎉 

I found why it's happening and how to work around it.

![Screen Shot 2020-09-03 at 4 10 13 pm](https://user-images.githubusercontent.com/45890/92089030-3a13ac80-ee00-11ea-96fd-274b3105608e.png)

I guess it might technically still be a bug in that VSCode or VSpaceCode are not correctly suppressing this behaviour. But IMO just turn this option off in your keyboard pref pane.

**Comment by stevenguh** [comment]
Thank you for solving this mystery. Seems like @philipfeldmann is using mac as well. Maybe this is also an option that he enabled. We should at least at this add this to known issue.

Not sure if we can work around this issue because we are using the input box in QuickPick API which is an input html element.
```html
<input class="input empty" autocorrect="off" autocapitalize="off" spellcheck="false" type="text" wrap="off" aria-describedby="quickInput_message" style="background-color: inherit; color: rgb(204, 204, 204);" placeholder="" title="" aria-label="Type to narrow down results." role="combobox" aria-haspopup="true" aria-autocomplete="list" aria-activedescendant="list_id_12_0">
```

**Comment by MarcoIeni** [comment]
> I guess it might technically still be a bug in that VSCode or VSpaceCode are not correctly suppressing this behaviour. 

I don't have a mac, so I can't reproduce this.

What's the input that is provided to vscode ultimately?

Because if I press `SPC .` I obtain the error `. is undefined`, while you obtain `._ is undefined`

If the input is `SPC .` you can add the following to your `settings.json`:

```
    "vspacecode.bindingOverrides": [
        {
            "keys": ["."],
            "name": "Commands...",
            "type": "command",
            "command": "workbench.action.showCommands"
        }
    ],
```

**Comment by stevenguh** [comment]
I think the input is probably `.<spc>`. Mac just insert a period before the second space just it's just like copied and pasted `.<spc>`.

Adding an overrides is a good work around idea. I just tested it, it only works if the `keys` is `.<spc>`
```
    "vspacecode.bindingOverrides": [
        {
            "keys": [". "],
            "name": "Commands...",
            "type": "command",
            "command": "workbench.action.showCommands"
        }
    ]
```

**Comment by MarcoIeni** [comment]
If one of these workaround works for Jack and Philip we can add it to the "known issue" section.
If you would like one of you can do the PR, too :)

**Comment by philipfeldmann** [comment]
> Ah Ha! 🎉
> 
> I found why it's happening and how to work around it.
> 
> ![Screen Shot 2020-09-03 at 4 10 13 pm](https://user-images.githubusercontent.com/45890/92089030-3a13ac80-ee00-11ea-96fd-274b3105608e.png)
> 
> I guess it might technically still be a bug in that VSCode or VSpaceCode are not correctly suppressing this behaviour. But IMO just turn this option off in your keyboard pref pane.

Thanks for solving this. Some default mac options are just plain stupid... 
In my opinion it might be enough to just mention this in the docs for mac users. I don't know why anyone into programming would turn this setting on anyway.

**Comment by MarcoIeni** [comment]
> In my opinion it might be enough to just mention this in the docs for mac users.

If you guys can try one of the proposed solutions we can add them in the docs if they work. Maybe some users are using this keyboard setting and they would like a workaround.

**Comment by philipfeldmann** [comment]
> > In my opinion it might be enough to just mention this in the docs for mac users.
> 
> If you guys can try one of the proposed solutions we can add them in the docs if they work. Maybe some users are using this keyboard setting and they would like a workaround.

I tested the override workaround and it works for me.

**Comment by MarcoIeni** [comment]
Thank you. Mine, or the one from Steven?

**Comment by philipfeldmann** [comment]
> Thank you. Mine, or the one from Steven?

Yours :)

**Comment by MarcoIeni** [comment]
solved in https://github.com/VSpaceCode/vspacecode.github.io/commit/17f6a4e6077bed665bd3ed9ce09470f6fb5a6bba

**Comment by benediktms** [comment]
I also had an issue where there was a delay when pressing space. Turns out this was because space is also my vim leader key. Rebinding it to something else solved the issue. Not sure if this is solvable?
