### ISSUE TITLE
Create a documentation website

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#97]
**Is your feature request related to a problem? Please describe.**
With the update coming from [this](https://github.com/VSpaceCode/vscode-which-key/pull/14) pull request (which I will review soon ^^') I had some thoughts:

- The README of vscode-which-key is becoming too long
- That feature is of interest of both VSpaceCode and vscode-which-key
- There is some overlap between the README of the two projects

**Describe the solution you'd like**
I propose to create a documentation website, similar to the one of [spacemacs](https://develop.spacemacs.org/doc/DOCUMENTATION.html) itself.

We could deploy it in another repo of this organization called `vspacecode.github.io` through github pages. In this way, it's domain will be https://vspacecode.github.io/

If we have external documentation, both the READMEs of the two project could be reduced to something like:

* overview of the project
* GIF
* installation
* links to all the resources

Customization, for example, should be explained in the external documentation website. In this way, users will be able to quickly read the README and get started. They will study how to customize their experience when and if they'll need it.

**Tasks**
- [ ] decide which framework to use among:
  - [mdbook](https://rust-lang.github.io/mdBook/)
  - https://readthedocs.org
  - https://docusaurus.io/en/
  - [git book](https://www.gitbook.com/) (No). See [1](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning), [2](https://news.ycombinator.com/item?id=22856602) and [3](https://v2.docusaurus.io/docs/#gitbook).
- [ ] should we create one website for VSpaceCode and one for vs-which-key?

**Comment by stevenguh** [comment]
yeah...it's getting really long to explain things, and it's not really ideal to be on a README anymore. I think ideally each repo should have their own doc since `which-key` is standalone thing, and `VSpaceCode` builds on-top of that with other features (Superset).

I looked around for a bit a while back, there are some options out there like https://readthedocs.org, https://docusaurus.io/en/.  Any one of the seems to be fine, but I haven't looked too much into it. docusaurus might be a little better that we will be hosting the website instead of readthedocs. I am thinking anything that's easy to maintain and use markdown would be good. Btw, I probably won't have the capacity to create a website in the short term.

**Comment by MarcoIeni** [comment]
> I am thinking anything that's easy to maintain and use markdown would be good.

Sure, no css, html and javascript. Just a static website built from markdown files.

> Btw, I probably won't have the capacity to create a website in the short term.

Our approach should be to put issues in the wild where we describe what should be done. Hopefully someone will show up and do it, or there will be a rainy Sunday where me or you are bored :)

> I think ideally each repo should have their own doc since `which-key` is standalone thing, and `VSpaceCode` builds on-top of that with other features (Superset).

If with "their own doc" you mean same website but different "chapters" of the docs, that's what I was thinking, too.

I know https://www.gitbook.com/ and https://rust-lang.github.io/mdBook/

We should evaluate all these alternatives

**Comment by stevenguh** [comment]
> Sure, no css, html and javascript. Just a static website built from markdown files.

I think it's good as long as we can separate the content (md) from the style (css, html, javascript). We probably should be able to control to style in the future if needed. I am just thinking by default the tool will generate from md and will also have knobs to tune to look and feel if needed.

> Our approach should be to put issues in the wild where we describe what should be done. Hopefully someone will show up and do it, or there will be a rainy Sunday where me or you are bored :)

Sounds good :)

> If with "their own doc" you mean same website but different "chapters" of the docs, that's what I was thinking, too.

I was thinking like two websites it might be clearer that way? But a one website that has a subset of the doc ("chapters")  dedicated to the `vscode-which-key` is also fine with me.

Right, forgot about gitbook.

Maybe it's good to put up some criteria. Here are some that I am thinking
- Build from md (separation of style and content)
- Able to store and link static asset
- Self-hosting on github
- Allow customization but have a default style (so we can just start with a basic style)

**Comment by MarcoIeni** [comment]
GitBook does not look good. See [1](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning) and [2](https://news.ycombinator.com/item?id=22856602).

**Comment by MarcoIeni** [comment]
From what I have seen in 20-30 minutes:
- if we want to have a full website with more customization options docusaurus seems the way to go
- if we want a simple book I would choose mdbook (I like rust, so I might be biased here

**Comment by stevenguh** [comment]
That aligns with my thinking as well.
- docusaurus is powerful and can build a full website (a [comparison](https://v2.docusaurus.io/docs/#comparison-with-other-tools) on their website)
- mdbook seems like to be easier to setup and it's simpler

If I am starting it, I would probably start right into docusaurus since I have experience in React (I am also biased :p) so we can have a nice website like spacemacs. I am also okay with us starting something simpler to document things with mdbook for now, and migrate if we have time to build a website. Since they are based on md, I am imaging that it would be all the hard to migrate.

**Comment by MarcoIeni** [comment]
setting up website with github actions is time consuming and migrating might be painful. If our final goal is docusaurus, let's start directly with this one and choose a minimal template to start.

At this point, having two full blown websites like docusaurus for both VSpaceCode and vscode-which-key seems an overkill to me, right?

**Comment by stevenguh** [comment]
That sounds good it me. Let's start with one website `VSpaceCode` if it starts getting confusing, we can always break it down.

**Comment by MarcoIeni** [comment]
Have you used docusaurus before? I saw that there is v2 in alpha and they suggest that one for new websites. Should we use that or v1?

**Comment by stevenguh** [comment]
I haven't not. But it seems like the the v2 alpha is close to beta, and many of open source projects are using v2. like https://create-react-app.dev and https://redux.js.org. I would suggest to start with v2 especially it generates a single page app (which is way snappier in navigating the doc pages)

**Comment by MarcoIeni** [comment]
I opened https://github.com/VSpaceCode/vspacecode.github.io/issues/1 which summarizes what we have written here.

As we said, any help is really appreciated!
