### ISSUE TITLE
Add new buffer submenu [new contributors only] 🐣

### ISSUE THREAD

**Issue by MarcoIeni** [VSpaceCode/VSpaceCode#99]
**Is your feature request related to a problem? Please describe.**
`SPC b N` in spacemacs (real one, not VSpaceCode) opens the "New buffer" submenu:

![image](https://user-images.githubusercontent.com/11428655/92955106-dc690b00-f464-11ea-8ea1-98a564b92711.png)

**Describe the solution you'd like**
You should add these key bindings to VSpaceCode.
Currently `SPC b N` opens a new scratch buffer.

https://github.com/VSpaceCode/VSpaceCode/blob/90e93b8a356f01156bb60f5dd7b41dcfb60277ed/package.json#L227-L232

This is wrong and `SPC b s` does the same thing, so you have to change this in order to reproduce spacemacs behavior.

You can even implement only a few of the spacemacs key bindings. In this case, we will accept the pull request and we will update this issue by specifying the missing key bindings that were not covered by the pull request.

**Additional context**
We have just reached 600 stars on GitHub and this is great, thanks! 🎉
But I would like more people to partecipate on this project.
Adding "good first issue" labels was not enough, so I am going one step further..This issue can be solved only by new contributors, i.e. people not listed [here](https://github.com/VSpaceCode/VSpaceCode/graphs/contributors). 😏

If you want to do this, please leave a comment and we will assign the issue to you. If you want clarifications, we are here to help you. 😀

Come on future VSpaceCode fellows, join us, I know you can do it! 💪

**Comment by stevenguh** [comment]
Implemented the new buffer with split options in eafc98ff6c6d05836c43f63eb185b21d50c8eecb. I want to release v0.8.0 soon, sorry breaking the 🐥 rule 😅

**Comment by stevenguh** [comment]
@MarcoIeni Do you think what we have is enough to release and close out this issue?

**Comment by MarcoIeni** [comment]
I don't think I have the time to do it today. Let's close this issue and ship the new version. I will reopen a new issue if there are some key bindings missing that could be added.

**Comment by stevenguh** [comment]
Closed :) And a new version is shipped. If there anything missing we can ship in as a "patch" version easily
